-- PostgreSQL Backup
-- Company: 7229a30d (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-09 13:45:28
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: sale_items (2 rows)
COPY sale_items (id, sale_id, quantity, original_price, discount_amount, cost_price, item_type, product_id, unit_price, tax_rate, price_tier_id, promotion_id, notes, treatment_id) FROM stdin;
5f3fc363-1509-4c0f-9fef-13aa5befb12b	3b066510-c225-4535-a6e3-34bd9cd8491a	1	300000	0	0	treatment	\N	300000	0	\N	\N		1e8909ad-3006-4df7-9d68-2c1e808b6fe5
5976fc2a-5933-4bd0-8245-4ae4ecf19b24	fa13132c-bc7f-4e71-882e-db152bcbc06d	1	1e+06	0	0	product	27129bd8-762c-409d-a125-1dc344d192a4	1e+06	0	\N	\N		\N
\.

-- Table: sale_payments (2 rows)
COPY sale_payments (amount, reference_number, card_last_4, notes, created_at, id, sale_id, payment_method) FROM stdin;
333000				2026-05-07 12:05:58	48e98854-5f6e-4cf1-9007-7e26cb81631f	3b066510-c225-4535-a6e3-34bd9cd8491a	CASH
1e+06				2026-05-09 06:44:42	3aa47ffa-40f1-4e56-b6a2-9bb01126a888	fa13132c-bc7f-4e71-882e-db152bcbc06d	CASH
\.

-- Table: purchase_order_items (1 rows)
COPY purchase_order_items (unit_price, tax_rate, discount_rate, id, po_id, product_id, qty_po, qty_receive) FROM stdin;
0	0	0	f8071a0f-1414-4141-a5b5-74d2b313aeff	675e6cbf-ee71-4a3d-8150-fbf9287bc33a	27129bd8-762c-409d-a125-1dc344d192a4	1	0
\.

-- Table: cash_drawer_transactions (4 rows)
COPY cash_drawer_transactions (type, amount, sale_id, payment_method, created_at, created_by, id, cash_drawer_id, balance_after, reason) FROM stdin;
OPENING	10000	\N	\N	2026-05-05 22:30:33	e86212b9-a748-49bd-85a3-ed5ca2f5bf45	42064749-5603-44cf-b788-f9ece15e82e6	52d21832-fd33-41ec-9fd0-516ea936aab9	10000	Opening cash drawer
OPENING	500000	\N	\N	2026-05-07 12:04:03	b2f6f967-35b6-40d3-8d15-d308140b67d7	9cc2c5c6-747f-40af-9b92-f38466fa5f96	1e8c0ea4-ae43-4e7a-857a-72dac322d60f	500000	Opening cash drawer
CASH_IN	333000	3b066510-c225-4535-a6e3-34bd9cd8491a	\N	2026-05-07 12:05:58	b2f6f967-35b6-40d3-8d15-d308140b67d7	57701d0e-dabc-4fc3-a946-853019661574	1e8c0ea4-ae43-4e7a-857a-72dac322d60f	833000	Penjualan #SLS-20260507-638
CASH_IN	1e+06	fa13132c-bc7f-4e71-882e-db152bcbc06d	\N	2026-05-09 06:44:42	b2f6f967-35b6-40d3-8d15-d308140b67d7	7f026472-8054-4980-8748-1749f23faaab	1e8c0ea4-ae43-4e7a-857a-72dac322d60f	1.833e+06	Penjualan #SLS-20260509-204
\.

-- Table: promotions (1 rows)
COPY promotions (usage_limit, promotion_type, end_date, usage_count, name, description, discount_value, max_discount_amount, start_time, end_time, min_purchase_amount, created_at, id, code, scope, buy_quantity, get_quantity, start_date, is_active) FROM stdin;
\N	PERCENTAGE	2026-04-01 07:00:00	0	dfsdfsd	testtt	10	\N	\N	\N	0	2026-04-12 13:30:20	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001	ALL	1	1	2026-04-01 07:00:00	true
\.

-- Table: units_of_measure (2 rows)
COPY units_of_measure (is_active, created_at, company_id, id, code, name, description) FROM stdin;
true	2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product
true	2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad
\.

