-- PostgreSQL Backup
-- Company: 7229a30d (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-06 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: purchase_order_items (1 rows)
COPY purchase_order_items (discount_rate, id, po_id, product_id, qty_po, qty_receive, unit_price, tax_rate) FROM stdin;
0	f8071a0f-1414-4141-a5b5-74d2b313aeff	675e6cbf-ee71-4a3d-8150-fbf9287bc33a	27129bd8-762c-409d-a125-1dc344d192a4	1	0	0	0
\.

-- Table: cash_drawer_transactions (1 rows)
COPY cash_drawer_transactions (amount, balance_after, sale_id, reason, created_at, created_by, id, cash_drawer_id, type, payment_method) FROM stdin;
10000	10000	\N	Opening cash drawer	2026-05-05 22:30:33	e86212b9-a748-49bd-85a3-ed5ca2f5bf45	42064749-5603-44cf-b788-f9ece15e82e6	52d21832-fd33-41ec-9fd0-516ea936aab9	OPENING	\N
\.

-- Table: promotions (1 rows)
COPY promotions (end_date, code, min_purchase_amount, max_discount_amount, buy_quantity, usage_limit, description, promotion_type, start_time, end_time, is_active, start_date, id, scope, discount_value, get_quantity, usage_count, created_at, name) FROM stdin;
2026-04-01 07:00:00	DP00001	0	\N	1	\N	testtt	PERCENTAGE	\N	\N	true	2026-04-01 07:00:00	5936bddd-a809-41d8-9044-3d91d6a2e6f9	ALL	10	1	0	2026-04-12 13:30:20	dfsdfsd
\.

-- Table: units_of_measure (2 rows)
COPY units_of_measure (name, description, is_active, created_at, company_id, id, code) FROM stdin;
Piece	satuan product	true	2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc
sadsa	sadsad	true	2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3	sad
\.

