-- PostgreSQL Backup
-- Company: 7229a30d (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-08 11:00:01
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: sale_items (1 rows)
COPY sale_items (sale_id, original_price, notes, item_type, treatment_id, product_id, quantity, unit_price, discount_amount, tax_rate, price_tier_id, promotion_id, cost_price, id) FROM stdin;
3b066510-c225-4535-a6e3-34bd9cd8491a	300000		treatment	1e8909ad-3006-4df7-9d68-2c1e808b6fe5	\N	1	300000	0	0	\N	\N	0	5f3fc363-1509-4c0f-9fef-13aa5befb12b
\.

-- Table: sale_payments (1 rows)
COPY sale_payments (created_at, id, sale_id, payment_method, amount, reference_number, card_last_4, notes) FROM stdin;
2026-05-07 12:05:58	48e98854-5f6e-4cf1-9007-7e26cb81631f	3b066510-c225-4535-a6e3-34bd9cd8491a	CASH	333000			
\.

-- Table: purchase_order_items (1 rows)
COPY purchase_order_items (id, po_id, product_id, qty_po, qty_receive, unit_price, tax_rate, discount_rate) FROM stdin;
f8071a0f-1414-4141-a5b5-74d2b313aeff	675e6cbf-ee71-4a3d-8150-fbf9287bc33a	27129bd8-762c-409d-a125-1dc344d192a4	1	0	0	0	0
\.

-- Table: cash_drawer_transactions (3 rows)
COPY cash_drawer_transactions (sale_id, payment_method, reason, created_at, created_by, id, type, amount, cash_drawer_id, balance_after) FROM stdin;
\N	\N	Opening cash drawer	2026-05-05 22:30:33	e86212b9-a748-49bd-85a3-ed5ca2f5bf45	42064749-5603-44cf-b788-f9ece15e82e6	OPENING	10000	52d21832-fd33-41ec-9fd0-516ea936aab9	10000
\N	\N	Opening cash drawer	2026-05-07 12:04:03	b2f6f967-35b6-40d3-8d15-d308140b67d7	9cc2c5c6-747f-40af-9b92-f38466fa5f96	OPENING	500000	1e8c0ea4-ae43-4e7a-857a-72dac322d60f	500000
3b066510-c225-4535-a6e3-34bd9cd8491a	\N	Penjualan #SLS-20260507-638	2026-05-07 12:05:58	b2f6f967-35b6-40d3-8d15-d308140b67d7	57701d0e-dabc-4fc3-a946-853019661574	CASH_IN	333000	1e8c0ea4-ae43-4e7a-857a-72dac322d60f	833000
\.

-- Table: promotions (1 rows)
COPY promotions (start_date, name, description, scope, min_purchase_amount, buy_quantity, start_time, end_date, is_active, get_quantity, id, code, promotion_type, max_discount_amount, end_time, usage_limit, usage_count, discount_value, created_at) FROM stdin;
2026-04-01 07:00:00	dfsdfsd	testtt	ALL	0	1	\N	2026-04-01 07:00:00	true	1	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001	PERCENTAGE	\N	\N	\N	0	10	2026-04-12 13:30:20
\.

-- Table: units_of_measure (2 rows)
COPY units_of_measure (code, name, description, is_active, created_at, company_id, id) FROM stdin;
pc	Piece	satuan product	true	2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b
sad	sadsa	sadsad	true	2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3
\.

