-- PostgreSQL Backup
-- Company: 7229a30d (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-05 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: promotions (1 rows)
COPY promotions (created_at, buy_quantity, start_time, end_time, usage_count, scope, discount_value, min_purchase_amount, max_discount_amount, is_active, name, description, start_date, end_date, usage_limit, id, code, promotion_type, get_quantity) FROM stdin;
2026-04-12 13:30:20	1	\N	\N	0	ALL	10	0	\N	true	dfsdfsd	testtt	2026-04-01 07:00:00	2026-04-01 07:00:00	\N	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001	PERCENTAGE	1
\.

-- Table: units_of_measure (2 rows)
COPY units_of_measure (id, code, name, description, is_active, created_at, company_id) FROM stdin;
6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product	true	2026-03-10 12:13:39	\N
937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad	true	2026-03-10 12:18:45	\N
\.

