-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-04 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (id, email, password, role, status, company_id, created_at, updated_at, username, full_name, last_login, is_active, phone) FROM stdin;
583e3b50-e159-43bf-bd8d-e91b79975a0a	fikriawan2007@gmail.com	$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	admin	active	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-18 11:11:38	2026-05-04 09:38:16	budifikri	Mochammad Budi FIkriawan	2026-05-04 09:38:16	true	\N
a0624492-9ab0-4dbb-8d60-a1eea1c20614	dsf@gmail.com	$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	cashier	active	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-27 08:50:12	2026-05-04 09:39:23	kasir1	Kasir 1	2026-04-29 11:12:41	true	088888
\.

-- Table: warehouses (2 rows)
COPY warehouses (id, name, type, phone, created_at, updated_at, code, status, address, city, manager_id, company_id, is_active) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	TOKO123	MAIN	+1234567890	2026-02-19 17:33:22	2026-03-03 20:16:10	TK	active	123 Test Street, Test City	Test City	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true
7faf63da-41f0-465e-ad68-48d40b6a135f	Second Warehouse 20260305T07203	BRANCH	+1234567890	2026-03-05 14:20:37	2026-03-10 20:48:20	WH2-20260305T07203	inactive	456 Transfer Street	Transfer City	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	false
\.

-- Table: customers (1 rows)
COPY customers (bank_account_name, is_active, id, phone, city, status, bank_branch, tier, lastPurchaseDate, updated_at, credit_balance, customer_code, name, address, loyalty_points, company_id, bank_account_number, created_at, email, credit_limit, total_purchases, bank_name) FROM stdin;
	true	b129a403-17d5-491c-95e0-2b8165f3d237	ewr	ewr	active		BRONZE	\N	2026-05-04 09:40:16	0	CUST-20260423T00425	were	ewrew	0	7229a30d-bb06-4e01-80d3-4162cabf93d9		2026-04-23 07:42:53	were	0	0	
\.

-- Table: suppliers (3 rows)
COPY suppliers (id, payment_terms, is_active, email, tax_id, status, created_at, code, name, phone, city, credit_limit, updated_at, contact_person, address, company_id, notes) FROM stdin;
474a9674-122b-4f92-b6ab-7f9c683b2063	NET_30	true	supplier_20260303T07062@example.com	TAX-20260303T07062	active	2026-03-03 14:06:24	SUP-1772521584647	Test Supplier 20260303T07062	+1234567890	Supplier City	10000	2026-03-03 14:06:24	John Doe	123 Supplier Street	7229a30d-bb06-4e01-80d3-4162cabf93d9	Test supplier created via API
53412491-3ae7-48f9-ada7-3a68d65bf5f0	NET_30	false	supplier_20260303T07431@example.com	TAX-20260303T07431	inactive	2026-03-03 14:43:19	SUP-1772523799582	Test Supplier 20260303T07431	+1234567890	Supplier City	10000	2026-03-03 20:07:58	John Doe	123 Supplier Street	7229a30d-bb06-4e01-80d3-4162cabf93d9	Test supplier created via API
57658cd5-f6df-4f22-80bd-a070fc1fa4a8	NET_30	true	fdf@gfg	dsf	active	2026-02-20 15:03:19	SUP-1771574599094	testt	fdf	sddfdsf	0	2026-03-03 20:10:25	dfd	dfgdfg	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N
\.

-- Table: sales (1 rows)
COPY sales (total_amount, loyalty_points_redeemed, sale_date, id, warehouse_id, cash_drawer_id, status, subtotal, tax_amount, discount_amount, paid_amount, sale_number, customer_id, change_amount, loyalty_points_earned, notes, created_at, updated_at, cashier_id, company_id) FROM stdin;
1800	0	2026-04-29 11:13:03	971d5a10-8c90-47e6-810e-92a5c50b1668	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	d1bb2074-55e0-47ca-9791-43b6b777e5b8	DONE	1800	0	200	2000	SLS-20260429-836	\N	200	0		2026-04-29 11:13:03	2026-04-29 11:13:03	a0624492-9ab0-4dbb-8d60-a1eea1c20614	7229a30d-bb06-4e01-80d3-4162cabf93d9
\.

-- Table: purchase_orders (1 rows)
COPY purchase_orders (po_number, supplier_id, tax_amount, created_by, approved_by, created_at, receive_date, id, payment_terms, status_receive, note_receive, total_amount, notes, updated_at, warehouse_id, order_date, expected_delivery, subtotal, discount_amount, receive_number, status_po, company_id) FROM stdin;
PO-26-93D9-000001	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	0	583e3b50-e159-43bf-bd8d-e91b79975a0a	\N	2026-04-29 11:11:28	2026-04-29 07:00:00	7b9a977d-e5fb-4b52-b519-651f4aaf8725	NET_30	receive	COMPLETE	2000		2026-04-29 11:12:03	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 07:00:00	2026-04-29 07:00:00	2000	0	\N	APPROVE	7229a30d-bb06-4e01-80d3-4162cabf93d9
\.

-- Table: cash_drawers (1 rows)
COPY cash_drawers (variance, deposit_invoice_id, updated_at, drawer_number, warehouse_id, created_at, expected_balance, opened_at, company_id, status, opening_balance, closing_balance, closed_at, notes, id, cashier_id) FROM stdin;
\N	\N	2026-04-29 11:13:03	CD-1777435966270	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 11:12:46	3000	2026-04-29 11:12:46	7229a30d-bb06-4e01-80d3-4162cabf93d9	OPEN	1000	\N	\N		d1bb2074-55e0-47ca-9791-43b6b777e5b8	a0624492-9ab0-4dbb-8d60-a1eea1c20614
\.

-- Table: stock_opnames (2 rows)
COPY stock_opnames (warehouse_id, user_id, opname_date, updated_at, company_id, total_selisih, opname_number, status, notes, created_at, is_opening, id) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-29 07:00:00	2026-05-04 09:40:01	7229a30d-bb06-4e01-80d3-4162cabf93d9	10000	OP-26-93d9-000001	approved		2026-04-29 11:15:02	false	b275dfbf-db21-4d95-8de3-4c3f9f948234
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-29 07:00:00	2026-04-29 17:05:44	7229a30d-bb06-4e01-80d3-4162cabf93d9	40000	OP-26-93d9-000002	approved		2026-04-29 11:54:48	false	6a1432fc-389d-43b3-a91b-b929232871eb
\.

-- Table: sale_items (1 rows)
COPY sale_items (id, product_id, quantity, unit_price, original_price, discount_amount, price_tier_id, promotion_id, sale_id, tax_rate, notes, cost_price) FROM stdin;
f297a26d-7176-44ef-8c55-ec504319f357	80315d11-94d9-4d03-bd79-25eade94738d	1	1800	2000	200	\N	5936bddd-a809-41d8-9044-3d91d6a2e6f9	971d5a10-8c90-47e6-810e-92a5c50b1668	0	DP00001 - dfsdfsd	1000
\.

-- Table: sale_payments (1 rows)
COPY sale_payments (reference_number, card_last_4, notes, created_at, id, sale_id, payment_method, amount) FROM stdin;
			2026-04-29 11:13:03	8af4fca4-a9c5-4090-b478-12e72f4ef2a9	971d5a10-8c90-47e6-810e-92a5c50b1668	CASH	2000
\.

-- Table: purchase_order_items (5 rows)
COPY purchase_order_items (qty_receive, unit_price, tax_rate, discount_rate, id, po_id, product_id, qty_po) FROM stdin;
1	2000	0	0	d63c8923-06b1-440e-ada0-1940c0429af3	7b9a977d-e5fb-4b52-b519-651f4aaf8725	80315d11-94d9-4d03-bd79-25eade94738d	1
1	2000	0	0	3984840a-5c7e-4db9-9d00-838b87ad9e3c	a66644fa-9734-4294-ad09-dac618dc6bf9	20afbb46-9d89-4087-adb2-f874552b7479	1
1	2000	0	0	d8109b67-7e63-4912-a2ec-8410c559f270	23b83e99-bbc2-467a-af9b-85c7f95b830c	20afbb46-9d89-4087-adb2-f874552b7479	1
1	2000	0	0	4bf1b3af-7996-4c59-9a84-815a075017ed	8e897c4a-d613-49e2-96a2-842cb69c18c5	20afbb46-9d89-4087-adb2-f874552b7479	1
0	1500	0	0	526b192a-b6ee-40c9-8401-c60239d5aeaa	3dd1a94e-2ee0-496f-bf4f-038bb8d39772	20afbb46-9d89-4087-adb2-f874552b7479	20
\.

-- Table: purchase_return_items (11 rows)
COPY purchase_return_items (po_item_id, product_id, quantity, amount, notes, tax_rate, return_id, unit_price, discount, id) FROM stdin;
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	2	4000		0	1928d830-324e-40d0-90d2-28d168d7b66f	2000	0	e52835b0-ff24-4e2b-8da2-e2ca53259f27
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000		0	1e827e52-fd70-44e1-994b-09c6c0f6f235	2000	0	c45ebbac-2ed0-40a1-b845-54db4f9a3aef
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000		0	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	2000	0	bbe572c8-08ba-440b-bd20-e644f405a6e3
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000		0	57460918-c311-41b2-9592-d636eb4e41dd	2000	0	5d5efc60-6a20-43fc-8741-36f11fef31b4
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000		0	32200a9d-642b-4d24-86b3-4425aebb07f8	2000	0	f7c888a6-40c9-4a71-a0bc-ee080f579bf4
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000		0	3e377261-afc7-41db-931e-e19586618b2e	2000	0	b4436858-3198-4609-9c8a-21dd962e5f39
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100		0	b089db6e-918c-4b41-a915-b2b70c0d528f	100	0	83fdc1fa-e25f-4ae4-b109-f746b2efd516
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100		0	ca735863-1f75-4312-8555-8e05fc1a3249	100	0	8e40512b-cbdf-4043-badf-3aaef32f9ac3
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100		0	1bcf88d2-aa2f-4b92-a8af-f96204be7335	100	0	b6541898-e4fd-4023-ba42-b5bec0e2171d
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100		0	8c017509-e77e-4508-aef0-825a5f5913e5	100	0	896d041c-f665-4e7c-97b5-feefdf77ccb7
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100		0	11204a47-3e0e-4b79-8b9e-9246163913fd	100	0	6dee9d1a-41cc-432a-b3b7-c10c763d4323
\.

-- Table: cash_drawer_transactions (2 rows)
COPY cash_drawer_transactions (id, amount, balance_after, payment_method, created_by, cash_drawer_id, type, sale_id, reason, created_at) FROM stdin;
b0146f36-52ec-4353-9f92-270ec52eb087	1000	1000	\N	a0624492-9ab0-4dbb-8d60-a1eea1c20614	d1bb2074-55e0-47ca-9791-43b6b777e5b8	OPENING	\N	Opening cash drawer	2026-04-29 11:12:46
d31b646c-7397-4f7b-9f11-da50d607ab12	2000	3000	\N	a0624492-9ab0-4dbb-8d60-a1eea1c20614	d1bb2074-55e0-47ca-9791-43b6b777e5b8	CASH_IN	971d5a10-8c90-47e6-810e-92a5c50b1668	Penjualan #SLS-20260429-836	2026-04-29 11:13:03
\.

-- Table: stock_opname_items (3 rows)
COPY stock_opname_items (opname_id, product_id, actual_quantity, difference, status, system_quantity, notes, cost_price, id) FROM stdin;
6a1432fc-389d-43b3-a91b-b929232871eb	80315d11-94d9-4d03-bd79-25eade94738d	10	10	done	0		1000	e1736130-f08d-4362-b72b-35f7e9e892af
6a1432fc-389d-43b3-a91b-b929232871eb	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	10	10	done	0		3000	6dbfff3a-05d2-48d5-b581-4aaf4188c298
b275dfbf-db21-4d95-8de3-4c3f9f948234	80315d11-94d9-4d03-bd79-25eade94738d	10	10	pending	0		1000	a779b574-7f50-445b-9196-e11dc82deab6
\.

-- Table: promotions (1 rows)
COPY promotions (start_time, id, description, promotion_type, discount_value, min_purchase_amount, max_discount_amount, get_quantity, name, start_date, created_at, code, is_active, scope, buy_quantity, end_date, end_time, usage_limit, usage_count) FROM stdin;
\N	5936bddd-a809-41d8-9044-3d91d6a2e6f9	testtt	PERCENTAGE	10	0	\N	1	dfsdfsd	2026-04-01 07:00:00	2026-04-12 13:30:20	DP00001	true	ALL	1	2026-04-01 07:00:00	\N	\N	0
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (unit_price, is_active, created_at, id, product_id, tier_name, min_quantity, max_quantity) FROM stdin;
4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1	3	\N
4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2	6	\N
3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3	12	\N
1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b	80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1	3	\N
1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2	3	\N
1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1	6	\N
1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3	12	\N
\.

-- Table: products (3 rows)
COPY products (company_id, sku, category_id, retail_price, tax_rate, updated_at, barcode, unit_id, reorder_point, description, cost_price, status, is_trackable, is_active, id, name, created_at) FROM stdin;
7229a30d-bb06-4e01-80d3-4162cabf93d9	200	88c17a83-e2e4-40c1-8487-aaf4dec60c99	5000	0	2026-04-11 08:15:37	100	d0ee1f31-abfc-41ac-848d-d501024f55f6	0	nasi gurame enak	3000	active	false	true	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Nasi Gurame	2026-03-17 09:48:30
7229a30d-bb06-4e01-80d3-4162cabf93d9	201	88c17a83-e2e4-40c1-8487-aaf4dec60c99	2000	0	2026-04-13 08:04:49	101	d0ee1f31-abfc-41ac-848d-d501024f55f6	0	\N	1000	active	false	true	80315d11-94d9-4d03-bd79-25eade94738d	Nasi Padang	2026-03-30 07:51:35
7229a30d-bb06-4e01-80d3-4162cabf93d9	202	88c17a83-e2e4-40c1-8487-aaf4dec60c99	500	0	2026-04-01 14:52:17	102	d0ee1f31-abfc-41ac-848d-d501024f55f6	0	Nasi Pecel Enak	200	active	false	true	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	nasi pecel	2026-02-20 16:19:35
\.

-- Table: categories (4 rows)
COPY categories (id, code, name, description, parent_id, company_id, is_active, created_at) FROM stdin;
98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf	Nonfood	barang nonfood	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19
88c17a83-e2e4-40c1-8487-aaf4dec60c99	TEST01	Test Kategori Baru		\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34
0ee6e45f-6577-4f27-bee4-5740ca57d1aa	TEST02	Kategori Test Baru		\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-23 08:24:49
f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm	Minuman	daftar minuman	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19
\.

-- Table: units_of_measure (5 rows)
COPY units_of_measure (id, code, name, description, is_active, created_at, company_id) FROM stdin;
80a309c7-946b-418b-8c01-e66e0a8c1722	un	Unit	sdfsdf	true	2026-04-23 08:24:29	7229a30d-bb06-4e01-80d3-4162cabf93d9
d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS	unit	true	2026-02-24 10:59:45	7229a30d-bb06-4e01-80d3-4162cabf93d9
2cf54205-b490-42d7-ad99-2311482e9b07	213	21321	2132	true	2026-02-20 16:20:08	7229a30d-bb06-4e01-80d3-4162cabf93d9
6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product	true	2026-03-10 12:13:39	\N
937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad	true	2026-03-10 12:18:45	\N
\.

