-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-04-26 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (username, full_name, role, status, created_at, updated_at, last_login, is_active, id, email, password, company_id, phone) FROM stdin;
budifikri	Mochammad Budi FIkriawan	admin	active	2026-02-18 11:11:38	2026-04-26 10:08:58	2026-04-26 10:08:58	true	583e3b50-e159-43bf-bd8d-e91b79975a0a	fikriawan2007@gmail.com	$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N
kasir1	Kasir 1	cashier	active	2026-03-27 08:50:12	2026-04-26 10:49:53	2026-04-26 10:49:53	true	a0624492-9ab0-4dbb-8d60-a1eea1c20614	dsf@gmail.com	$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	7229a30d-bb06-4e01-80d3-4162cabf93d9	088888
\.

-- Table: warehouses (2 rows)
COPY warehouses (name, type, status, updated_at, is_active, id, code, address, city, phone, manager_id, company_id, created_at) FROM stdin;
TOKO123	MAIN	active	2026-03-03 20:16:10	true	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	TK	123 Test Street, Test City	Test City	+1234567890	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-19 17:33:22
Second Warehouse 20260305T07203	BRANCH	inactive	2026-03-10 20:48:20	false	7faf63da-41f0-465e-ad68-48d40b6a135f	WH2-20260305T07203	456 Transfer Street	Transfer City	+1234567890	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-05 14:20:37
\.

-- Table: customers (1 rows)
COPY customers (address, credit_balance, bank_account_number, bank_account_name, updated_at, tier, total_purchases, bank_name, created_at, is_active, city, bank_branch, id, email, phone, status, loyalty_points, credit_limit, lastPurchaseDate, company_id, customer_code, name) FROM stdin;
ewrew	0			2026-04-23 07:43:12	BRONZE	0		2026-04-23 07:42:53	true	ewr		b129a403-17d5-491c-95e0-2b8165f3d237	were	ewr	active	0	0	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	CUST-20260423T00425	were
\.

-- Table: suppliers (3 rows)
COPY suppliers (contact_person, status, is_active, name, tax_id, notes, created_at, updated_at, email, phone, address, city, id, code, payment_terms, credit_limit, company_id) FROM stdin;
John Doe	active	true	Test Supplier 20260303T07062	TAX-20260303T07062	Test supplier created via API	2026-03-03 14:06:24	2026-03-03 14:06:24	supplier_20260303T07062@example.com	+1234567890	123 Supplier Street	Supplier City	474a9674-122b-4f92-b6ab-7f9c683b2063	SUP-1772521584647	NET_30	10000	7229a30d-bb06-4e01-80d3-4162cabf93d9
John Doe	inactive	false	Test Supplier 20260303T07431	TAX-20260303T07431	Test supplier created via API	2026-03-03 14:43:19	2026-03-03 20:07:58	supplier_20260303T07431@example.com	+1234567890	123 Supplier Street	Supplier City	53412491-3ae7-48f9-ada7-3a68d65bf5f0	SUP-1772523799582	NET_30	10000	7229a30d-bb06-4e01-80d3-4162cabf93d9
dfd	active	true	testt	dsf	\N	2026-02-20 15:03:19	2026-03-03 20:10:25	fdf@gfg	fdf	dfgdfg	sddfdsf	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	SUP-1771574599094	NET_30	0	7229a30d-bb06-4e01-80d3-4162cabf93d9
\.

-- Table: sales (3 rows)
COPY sales (cashier_id, cash_drawer_id, tax_amount, discount_amount, created_at, id, sale_number, warehouse_id, company_id, subtotal, customer_id, sale_date, status, total_amount, loyalty_points_earned, loyalty_points_redeemed, updated_at, paid_amount, change_amount, notes) FROM stdin;
a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	0	4000	2026-04-24 07:07:03	30168143-ab1b-49ae-8415-9202850c4c3c	SLS-20260424-887	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	7229a30d-bb06-4e01-80d3-4162cabf93d9	36000	\N	2026-04-24 07:07:03	DONE	36000	3	0	2026-04-24 07:07:03	40000	4000	
a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	0	200	2026-04-25 11:35:47	a5faf962-24ef-4b9d-9b58-72a96dfb085b	SLS-20260425-199	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	7229a30d-bb06-4e01-80d3-4162cabf93d9	1800	\N	2026-04-25 11:35:47	DONE	1800	0	0	2026-04-25 11:35:47	2000	200	
a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	0	200	2026-04-25 11:36:25	9ed0899e-d9d5-4914-a0dc-692b1a44aaa6	SLS-20260425-306	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	7229a30d-bb06-4e01-80d3-4162cabf93d9	1800	\N	2026-04-25 11:36:25	DONE	1800	0	0	2026-04-25 11:36:25	2000	200	
\.

-- Table: purchase_orders (3 rows)
COPY purchase_orders (status_po, note_receive, subtotal, tax_amount, updated_at, receive_number, expected_delivery, payment_terms, discount_amount, notes, approved_by, created_at, po_number, status_receive, id, supplier_id, order_date, total_amount, company_id, created_by, receive_date, warehouse_id) FROM stdin;
APPROVE	COMPLETE	420000	0	2026-04-24 06:58:15	\N	2026-04-24 06:57:23	NET_30	0		\N	2026-04-24 06:57:23	PO-26-93D9-000001	receive	2c2d6f41-802b-432a-8221-314226074ea9	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 06:57:23	420000	7229a30d-bb06-4e01-80d3-4162cabf93d9	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-24 07:00:00	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd
APPROVE	COMPLETE	200000	0	2026-04-24 07:05:47	\N	2026-04-24 07:03:04	NET_30	0		\N	2026-04-24 07:03:04	PO-26-93D9-000002	receive	344113bf-22c1-416d-b76f-04656cd5cb05	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 07:03:04	200000	7229a30d-bb06-4e01-80d3-4162cabf93d9	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-24 07:00:00	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd
VOID	\N	200000	0	2026-04-24 10:19:52	\N	2026-04-24 07:00:00	NET_30	0		\N	2026-04-24 10:06:24	PO-26-93D9-000003	DRAFT	5239eb24-6003-47a2-b0c3-f4f9190d5e27	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 07:00:00	200000	7229a30d-bb06-4e01-80d3-4162cabf93d9	583e3b50-e159-43bf-bd8d-e91b79975a0a	\N	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd
\.

-- Table: purchase_returns (1 rows)
COPY purchase_returns (warehouse_id, company_id, status, total_amount, updated_at, id, return_number, po_id, return_date, reason, created_by, approved_by, created_at, supplier_id) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	7229a30d-bb06-4e01-80d3-4162cabf93d9	APPROVED	30000	2026-04-24 12:39:30	e35d87c6-be99-4274-9411-14cf1a7a646b	PR-26-93d9-000001	00000000-0000-0000-0000-000000000000	2026-04-24 12:39:30		583e3b50-e159-43bf-bd8d-e91b79975a0a	00000000-0000-0000-0000-000000000000	2026-04-24 12:39:30	474a9674-122b-4f92-b6ab-7f9c683b2063
\.

-- Table: cash_drawers (1 rows)
COPY cash_drawers (variance, notes, deposit_invoice_id, updated_at, id, warehouse_id, expected_balance, opened_at, closed_at, created_at, cashier_id, opening_balance, closing_balance, drawer_number, company_id, status) FROM stdin;
\N		\N	2026-04-25 11:36:25	6b9a66f9-1479-4e46-a495-8ad9184d6afa	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	244000	2026-04-24 07:06:50	\N	2026-04-24 07:06:50	a0624492-9ab0-4dbb-8d60-a1eea1c20614	200000	\N	CD-1776989210284	7229a30d-bb06-4e01-80d3-4162cabf93d9	OPEN
\.

-- Table: stock_opnames (1 rows)
COPY stock_opnames (notes, created_at, updated_at, company_id, id, opname_number, warehouse_id, opname_date, user_id, status) FROM stdin;
	2026-04-25 07:42:14	2026-04-25 07:42:20	7229a30d-bb06-4e01-80d3-4162cabf93d9	28d72f1b-5684-4f61-8736-ef0bad863963	OP-26-93d9-000001	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-25 07:00:00	583e3b50-e159-43bf-bd8d-e91b79975a0a	approved
\.

-- Table: sale_items (3 rows)
COPY sale_items (original_price, discount_amount, price_tier_id, tax_rate, promotion_id, notes, id, sale_id, product_id, quantity, unit_price) FROM stdin;
2000	200	\N	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001 - dfsdfsd	fc415e48-30a5-408b-bc06-54a9a57331f1	30168143-ab1b-49ae-8415-9202850c4c3c	80315d11-94d9-4d03-bd79-25eade94738d	20	1800
2000	200	\N	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001 - dfsdfsd	267c7cbe-273b-43c3-b9a6-08353d5896c0	a5faf962-24ef-4b9d-9b58-72a96dfb085b	80315d11-94d9-4d03-bd79-25eade94738d	1	1800
2000	200	\N	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001 - dfsdfsd	af29295a-b997-4930-8d04-e5e86dd2642d	9ed0899e-d9d5-4914-a0dc-692b1a44aaa6	80315d11-94d9-4d03-bd79-25eade94738d	1	1800
\.

-- Table: sale_payments (3 rows)
COPY sale_payments (id, sale_id, payment_method, amount, reference_number, card_last_4, notes, created_at) FROM stdin;
2078af9a-9f7c-45aa-a77a-4a3b4c307162	30168143-ab1b-49ae-8415-9202850c4c3c	CASH	40000				2026-04-24 07:07:03
2c3116e0-2758-4e12-b80f-470d14d22720	a5faf962-24ef-4b9d-9b58-72a96dfb085b	CASH	2000				2026-04-25 11:35:47
6b7c4af5-4eaa-4f8d-99c7-062f68da54d5	9ed0899e-d9d5-4914-a0dc-692b1a44aaa6	CASH	2000				2026-04-25 11:36:25
\.

-- Table: purchase_order_items (9 rows)
COPY purchase_order_items (po_id, product_id, qty_po, qty_receive, unit_price, tax_rate, discount_rate, id) FROM stdin;
2c2d6f41-802b-432a-8221-314226074ea9	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	100	100	3000	0	0	0628622f-ef54-4760-b25b-43adbb9ae1e2
2c2d6f41-802b-432a-8221-314226074ea9	80315d11-94d9-4d03-bd79-25eade94738d	100	100	1000	0	0	6c36e9e9-6ebf-4421-862b-ee8e5ff3c82c
2c2d6f41-802b-432a-8221-314226074ea9	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	100	100	200	0	0	93bba8aa-553a-4bb8-8be8-564fedaa5709
344113bf-22c1-416d-b76f-04656cd5cb05	80315d11-94d9-4d03-bd79-25eade94738d	200	200	1000	0	0	f54e55ca-54b3-4287-b9c9-9287eba2c6ac
5239eb24-6003-47a2-b0c3-f4f9190d5e27	80315d11-94d9-4d03-bd79-25eade94738d	200	0	1000	0	0	ee3e88d6-4d99-44c8-bf6f-ca6470ccd386
a66644fa-9734-4294-ad09-dac618dc6bf9	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	3984840a-5c7e-4db9-9d00-838b87ad9e3c
23b83e99-bbc2-467a-af9b-85c7f95b830c	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	d8109b67-7e63-4912-a2ec-8410c559f270
8e897c4a-d613-49e2-96a2-842cb69c18c5	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	4bf1b3af-7996-4c59-9a84-815a075017ed
3dd1a94e-2ee0-496f-bf4f-038bb8d39772	20afbb46-9d89-4087-adb2-f874552b7479	20	0	1500	0	0	526b192a-b6ee-40c9-8401-c60239d5aeaa
\.

-- Table: purchase_return_items (12 rows)
COPY purchase_return_items (po_item_id, product_id, quantity, amount, id, return_id, unit_price, notes, discount, tax_rate) FROM stdin;
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	2	4000	e52835b0-ff24-4e2b-8da2-e2ca53259f27	1928d830-324e-40d0-90d2-28d168d7b66f	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	c45ebbac-2ed0-40a1-b845-54db4f9a3aef	1e827e52-fd70-44e1-994b-09c6c0f6f235	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	bbe572c8-08ba-440b-bd20-e644f405a6e3	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	5d5efc60-6a20-43fc-8741-36f11fef31b4	57460918-c311-41b2-9592-d636eb4e41dd	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	f7c888a6-40c9-4a71-a0bc-ee080f579bf4	32200a9d-642b-4d24-86b3-4425aebb07f8	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	b4436858-3198-4609-9c8a-21dd962e5f39	3e377261-afc7-41db-931e-e19586618b2e	2000		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100	83fdc1fa-e25f-4ae4-b109-f746b2efd516	b089db6e-918c-4b41-a915-b2b70c0d528f	100		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100	8e40512b-cbdf-4043-badf-3aaef32f9ac3	ca735863-1f75-4312-8555-8e05fc1a3249	100		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100	b6541898-e4fd-4023-ba42-b5bec0e2171d	1bcf88d2-aa2f-4b92-a8af-f96204be7335	100		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100	896d041c-f665-4e7c-97b5-feefdf77ccb7	8c017509-e77e-4508-aef0-825a5f5913e5	100		0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	100	6dee9d1a-41cc-432a-b3b7-c10c763d4323	11204a47-3e0e-4b79-8b9e-9246163913fd	100		0	0
00000000-0000-0000-0000-000000000000	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	10	30000	a0f2560a-119c-4b39-a40d-706e7786955c	e35d87c6-be99-4274-9411-14cf1a7a646b	3000		0	0
\.

-- Table: cash_drawer_transactions (4 rows)
COPY cash_drawer_transactions (type, amount, payment_method, created_at, created_by, cash_drawer_id, balance_after, sale_id, reason, id) FROM stdin;
OPENING	200000	\N	2026-04-24 07:06:50	a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	200000	\N	Opening cash drawer	0238030f-6162-4064-b3ea-6f0499e208f8
CASH_IN	40000	\N	2026-04-24 07:07:03	a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	240000	30168143-ab1b-49ae-8415-9202850c4c3c	Penjualan #SLS-20260424-887	87ccbfb5-8031-4722-91b2-5b7a2e2c4c20
CASH_IN	2000	\N	2026-04-25 11:35:47	a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	242000	a5faf962-24ef-4b9d-9b58-72a96dfb085b	Penjualan #SLS-20260425-199	a0ffb4a8-f799-476f-8738-10f9c72f0dae
CASH_IN	2000	\N	2026-04-25 11:36:25	a0624492-9ab0-4dbb-8d60-a1eea1c20614	6b9a66f9-1479-4e46-a495-8ad9184d6afa	244000	9ed0899e-d9d5-4914-a0dc-692b1a44aaa6	Penjualan #SLS-20260425-306	adf47d5f-be7a-4a4d-ac63-1dc12be03867
\.

-- Table: stock_opname_items (1 rows)
COPY stock_opname_items (product_id, system_quantity, actual_quantity, difference, notes, status, id, opname_id) FROM stdin;
b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	90	10	-80	broken	done	17afc51d-0cb9-460e-9c29-4a2c46a56c2d	28d72f1b-5684-4f61-8736-ef0bad863963
\.

-- Table: promotions (1 rows)
COPY promotions (description, discount_value, start_date, start_time, end_time, promotion_type, scope, max_discount_amount, usage_limit, min_purchase_amount, buy_quantity, is_active, usage_count, id, code, name, get_quantity, end_date, created_at) FROM stdin;
testtt	10	2026-04-01 07:00:00	\N	\N	PERCENTAGE	ALL	\N	\N	0	1	true	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001	dfsdfsd	1	2026-04-01 07:00:00	2026-04-12 13:30:20
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (unit_price, is_active, created_at, id, product_id, tier_name, min_quantity, max_quantity) FROM stdin;
4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1	3	\N
4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2	6	\N
3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3	12	\N
1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b	80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1	3	\N
1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2	3	\N
1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1	6	\N
1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3	12	\N
\.

-- Table: products (3 rows)
COPY products (barcode, name, category_id, unit_id, company_id, created_at, is_active, description, cost_price, retail_price, status, is_trackable, sku, reorder_point, updated_at, id, tax_rate) FROM stdin;
100	Nasi Gurame	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-17 09:48:30	true	nasi gurame enak	3000	5000	active	false	200	0	2026-04-11 08:15:37	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	0
101	Nasi Padang	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-30 07:51:35	true	\N	1000	2000	active	false	201	0	2026-04-13 08:04:49	80315d11-94d9-4d03-bd79-25eade94738d	0
102	nasi pecel	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-20 16:19:35	true	Nasi Pecel Enak	200	500	active	false	202	0	2026-04-01 14:52:17	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	0
\.

-- Table: categories (4 rows)
COPY categories (description, parent_id, company_id, is_active, created_at, id, code, name) FROM stdin;
barang nonfood	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf	Nonfood
	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34	88c17a83-e2e4-40c1-8487-aaf4dec60c99	TEST01	Test Kategori Baru
	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-23 08:24:49	0ee6e45f-6577-4f27-bee4-5740ca57d1aa	TEST02	Kategori Test Baru
daftar minuman	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm	Minuman
\.

-- Table: units_of_measure (5 rows)
COPY units_of_measure (id, code, name, description, is_active, created_at, company_id) FROM stdin;
80a309c7-946b-418b-8c01-e66e0a8c1722	un	Unit	sdfsdf	true	2026-04-23 08:24:29	7229a30d-bb06-4e01-80d3-4162cabf93d9
d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS	unit	true	2026-02-24 10:59:45	7229a30d-bb06-4e01-80d3-4162cabf93d9
2cf54205-b490-42d7-ad99-2311482e9b07	213	21321	2132	true	2026-02-20 16:20:08	7229a30d-bb06-4e01-80d3-4162cabf93d9
6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product	true	2026-03-10 12:13:39	\N
937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad	true	2026-03-10 12:18:45	\N
\.

