-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-04-16 11:36:02
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (password, role, company_id, created_at, phone, id, full_name, status, updated_at, last_login, is_active, username, email) FROM stdin;
$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	cashier	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-27 08:50:12	088888	a0624492-9ab0-4dbb-8d60-a1eea1c20614	Kasir 1	active	2026-04-13 15:03:52	2026-04-13 15:03:52	true	kasir1	dsf@gmail.com
$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	admin	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-18 11:11:38	\N	583e3b50-e159-43bf-bd8d-e91b79975a0a	Mochammad Budi FIkriawan	active	2026-04-16 07:17:28	2026-04-16 07:17:28	true	budifikri	fikriawan2007@gmail.com
\.

-- Table: warehouses (2 rows)
COPY warehouses (id, name, type, status, address, phone, company_id, created_at, code, city, manager_id, updated_at, is_active) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	TOKO123	MAIN	active	123 Test Street, Test City	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-19 17:33:22	TK	Test City	\N	2026-03-03 20:16:10	true
7faf63da-41f0-465e-ad68-48d40b6a135f	Second Warehouse 20260305T07203	BRANCH	inactive	456 Transfer Street	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-05 14:20:37	WH2-20260305T07203	Transfer City	\N	2026-03-10 20:48:20	false
\.

-- Table: suppliers (3 rows)
COPY suppliers (contact_person, phone, company_id, created_at, is_active, code, name, email, city, tax_id, address, payment_terms, credit_limit, updated_at, id, status, notes) FROM stdin;
John Doe	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-03 14:06:24	true	SUP-1772521584647	Test Supplier 20260303T07062	supplier_20260303T07062@example.com	Supplier City	TAX-20260303T07062	123 Supplier Street	NET_30	10000	2026-03-03 14:06:24	474a9674-122b-4f92-b6ab-7f9c683b2063	active	Test supplier created via API
John Doe	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-03 14:43:19	false	SUP-1772523799582	Test Supplier 20260303T07431	supplier_20260303T07431@example.com	Supplier City	TAX-20260303T07431	123 Supplier Street	NET_30	10000	2026-03-03 20:07:58	53412491-3ae7-48f9-ada7-3a68d65bf5f0	inactive	Test supplier created via API
dfd	fdf	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-20 15:03:19	true	SUP-1771574599094	testt	fdf@gfg	sddfdsf	dsf	dfgdfg	NET_30	0	2026-03-03 20:10:25	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	active	\N
\.

-- Table: purchase_order_items (4 rows)
COPY purchase_order_items (id, po_id, product_id, qty_po, qty_receive, unit_price, tax_rate, discount_rate) FROM stdin;
3984840a-5c7e-4db9-9d00-838b87ad9e3c	a66644fa-9734-4294-ad09-dac618dc6bf9	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0
d8109b67-7e63-4912-a2ec-8410c559f270	23b83e99-bbc2-467a-af9b-85c7f95b830c	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0
4bf1b3af-7996-4c59-9a84-815a075017ed	8e897c4a-d613-49e2-96a2-842cb69c18c5	20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0
526b192a-b6ee-40c9-8401-c60239d5aeaa	3dd1a94e-2ee0-496f-bf4f-038bb8d39772	20afbb46-9d89-4087-adb2-f874552b7479	20	0	1500	0	0
\.

-- Table: purchase_return_items (11 rows)
COPY purchase_return_items (po_item_id, product_id, quantity, notes, id, return_id, unit_price, amount, discount, tax_rate) FROM stdin;
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	2		e52835b0-ff24-4e2b-8da2-e2ca53259f27	1928d830-324e-40d0-90d2-28d168d7b66f	2000	4000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		c45ebbac-2ed0-40a1-b845-54db4f9a3aef	1e827e52-fd70-44e1-994b-09c6c0f6f235	2000	2000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		bbe572c8-08ba-440b-bd20-e644f405a6e3	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	2000	2000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		5d5efc60-6a20-43fc-8741-36f11fef31b4	57460918-c311-41b2-9592-d636eb4e41dd	2000	2000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		f7c888a6-40c9-4a71-a0bc-ee080f579bf4	32200a9d-642b-4d24-86b3-4425aebb07f8	2000	2000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		b4436858-3198-4609-9c8a-21dd962e5f39	3e377261-afc7-41db-931e-e19586618b2e	2000	2000	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		83fdc1fa-e25f-4ae4-b109-f746b2efd516	b089db6e-918c-4b41-a915-b2b70c0d528f	100	100	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		8e40512b-cbdf-4043-badf-3aaef32f9ac3	ca735863-1f75-4312-8555-8e05fc1a3249	100	100	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		b6541898-e4fd-4023-ba42-b5bec0e2171d	1bcf88d2-aa2f-4b92-a8af-f96204be7335	100	100	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		896d041c-f665-4e7c-97b5-feefdf77ccb7	8c017509-e77e-4508-aef0-825a5f5913e5	100	100	0	0
00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1		6dee9d1a-41cc-432a-b3b7-c10c763d4323	11204a47-3e0e-4b79-8b9e-9246163913fd	100	100	0	0
\.

-- Table: promotions (1 rows)
COPY promotions (usage_limit, code, promotion_type, min_purchase_amount, end_date, start_date, created_at, id, name, max_discount_amount, get_quantity, start_time, end_time, is_active, usage_count, description, scope, discount_value, buy_quantity) FROM stdin;
\N	DP00001	PERCENTAGE	0	2026-04-01 07:00:00	2026-04-01 07:00:00	2026-04-12 13:30:20	5936bddd-a809-41d8-9044-3d91d6a2e6f9	dfsdfsd	\N	1	\N	\N	true	0	testtt	ALL	10	1
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (unit_price, is_active, created_at, id, product_id, tier_name, min_quantity, max_quantity) FROM stdin;
1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2	3	\N
1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1	6	\N
1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3	12	\N
4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1	3	\N
4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2	6	\N
3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3	12	\N
1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b	80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1	3	\N
\.

-- Table: products (3 rows)
COPY products (updated_at, barcode, tax_rate, is_trackable, reorder_point, created_at, is_active, id, category_id, unit_id, cost_price, retail_price, company_id, description, status, sku, name) FROM stdin;
2026-04-11 08:15:37	100	0	false	0	2026-03-17 09:48:30	true	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	3000	5000	7229a30d-bb06-4e01-80d3-4162cabf93d9	nasi gurame enak	active	200	Nasi Gurame
2026-04-13 08:04:49	101	0	false	0	2026-03-30 07:51:35	true	80315d11-94d9-4d03-bd79-25eade94738d	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	1000	2000	7229a30d-bb06-4e01-80d3-4162cabf93d9		active	201	Nasi Padang
2026-04-01 14:52:17	102	0	false	0	2026-02-20 16:19:35	true	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	200	500	7229a30d-bb06-4e01-80d3-4162cabf93d9	Nasi Pecel Enak	active	202	nasi pecel
\.

-- Table: categories (3 rows)
COPY categories (name, description, parent_id, company_id, is_active, created_at, id, code) FROM stdin;
Minuman	daftar minuman	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm
Nonfood	barang nonfood	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf
makanan	nasi	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34	88c17a83-e2e4-40c1-8487-aaf4dec60c99	mkn
\.

-- Table: units_of_measure (4 rows)
COPY units_of_measure (created_at, company_id, id, code, name, description, is_active) FROM stdin;
2026-02-20 16:20:08	7229a30d-bb06-4e01-80d3-4162cabf93d9	2cf54205-b490-42d7-ad99-2311482e9b07	kg	KiloGram	berat	true
2026-02-24 10:59:45	7229a30d-bb06-4e01-80d3-4162cabf93d9	d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS	unit	true
2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product	true
2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad	true
\.

