-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-02 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (email, password, full_name, role, company_id, updated_at, last_login, phone, id, username, status, created_at, is_active) FROM stdin;
dsf@gmail.com	$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	Kasir 1	cashier	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-29 11:12:41	2026-04-29 11:12:41	088888	a0624492-9ab0-4dbb-8d60-a1eea1c20614	kasir1	active	2026-03-27 08:50:12	true
fikriawan2007@gmail.com	$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	Mochammad Budi FIkriawan	admin	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-05-02 06:55:07	2026-05-02 06:55:07	\N	583e3b50-e159-43bf-bd8d-e91b79975a0a	budifikri	active	2026-02-18 11:11:38	true
\.

-- Table: warehouses (2 rows)
COPY warehouses (status, address, city, phone, updated_at, id, manager_id, company_id, created_at, is_active, code, name, type) FROM stdin;
active	123 Test Street, Test City	Test City	+1234567890	2026-03-03 20:16:10	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-19 17:33:22	true	TK	TOKO123	MAIN
inactive	456 Transfer Street	Transfer City	+1234567890	2026-03-10 20:48:20	7faf63da-41f0-465e-ad68-48d40b6a135f	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-05 14:20:37	false	WH2-20260305T07203	Second Warehouse 20260305T07203	BRANCH
\.

-- Table: customers (1 rows)
COPY customers (customer_code, email, city, loyalty_points, total_purchases, bank_branch, is_active, credit_limit, created_at, phone, address, credit_balance, bank_account_number, bank_account_name, id, name, tier, status, company_id, bank_name, updated_at, lastPurchaseDate) FROM stdin;
CUST-20260423T00425	were	ewr	0	0		true	0	2026-04-23 07:42:53	ewr	ewrew	0			b129a403-17d5-491c-95e0-2b8165f3d237	were	BRONZE	active	7229a30d-bb06-4e01-80d3-4162cabf93d9		2026-04-23 07:43:12	\N
\.

-- Table: suppliers (3 rows)
COPY suppliers (credit_limit, status, contact_person, phone, address, company_id, created_at, is_active, name, payment_terms, notes, updated_at, email, city, tax_id, id, code) FROM stdin;
10000	active	John Doe	+1234567890	123 Supplier Street	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-03 14:06:24	true	Test Supplier 20260303T07062	NET_30	Test supplier created via API	2026-03-03 14:06:24	supplier_20260303T07062@example.com	Supplier City	TAX-20260303T07062	474a9674-122b-4f92-b6ab-7f9c683b2063	SUP-1772521584647
10000	inactive	John Doe	+1234567890	123 Supplier Street	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-03 14:43:19	false	Test Supplier 20260303T07431	NET_30	Test supplier created via API	2026-03-03 20:07:58	supplier_20260303T07431@example.com	Supplier City	TAX-20260303T07431	53412491-3ae7-48f9-ada7-3a68d65bf5f0	SUP-1772523799582
0	active	dfd	fdf	dfgdfg	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-20 15:03:19	true	testt	NET_30	\N	2026-03-03 20:10:25	fdf@gfg	sddfdsf	dsf	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	SUP-1771574599094
\.

-- Table: sales (1 rows)
COPY sales (sale_number, warehouse_id, cash_drawer_id, notes, updated_at, id, company_id, sale_date, status, subtotal, tax_amount, discount_amount, customer_id, cashier_id, total_amount, paid_amount, loyalty_points_earned, loyalty_points_redeemed, change_amount, created_at) FROM stdin;
SLS-20260429-836	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	d1bb2074-55e0-47ca-9791-43b6b777e5b8		2026-04-29 11:13:03	971d5a10-8c90-47e6-810e-92a5c50b1668	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-29 11:13:03	DONE	1800	0	200	\N	a0624492-9ab0-4dbb-8d60-a1eea1c20614	1800	2000	0	0	200	2026-04-29 11:13:03
\.

-- Table: purchase_orders (1 rows)
COPY purchase_orders (id, status_receive, note_receive, discount_amount, updated_at, payment_terms, total_amount, company_id, created_at, receive_date, po_number, status_po, subtotal, notes, receive_number, supplier_id, warehouse_id, order_date, expected_delivery, tax_amount, created_by, approved_by) FROM stdin;
7b9a977d-e5fb-4b52-b519-651f4aaf8725	receive	COMPLETE	0	2026-04-29 11:12:03	NET_30	2000	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-29 11:11:28	2026-04-29 07:00:00	PO-26-93D9-000001	APPROVE	2000		\N	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 07:00:00	2026-04-29 07:00:00	0	583e3b50-e159-43bf-bd8d-e91b79975a0a	\N
\.

-- Table: cash_drawers (1 rows)
COPY cash_drawers (company_id, variance, opened_at, deposit_invoice_id, id, status, created_at, updated_at, drawer_number, cashier_id, closing_balance, notes, warehouse_id, opening_balance, expected_balance, closed_at) FROM stdin;
7229a30d-bb06-4e01-80d3-4162cabf93d9	\N	2026-04-29 11:12:46	\N	d1bb2074-55e0-47ca-9791-43b6b777e5b8	OPEN	2026-04-29 11:12:46	2026-04-29 11:13:03	CD-1777435966270	a0624492-9ab0-4dbb-8d60-a1eea1c20614	\N		ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	1000	3000	\N
\.

-- Table: stock_opnames (2 rows)
COPY stock_opnames (warehouse_id, user_id, opname_date, status, notes, created_at, updated_at, id, company_id, total_selisih, is_opening, opname_number) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-29 07:00:00	draft		2026-04-29 11:15:02	2026-04-29 11:15:02	b275dfbf-db21-4d95-8de3-4c3f9f948234	7229a30d-bb06-4e01-80d3-4162cabf93d9	0	false	OP-26-93d9-000001
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-29 07:00:00	approved		2026-04-29 11:54:48	2026-04-29 17:05:44	6a1432fc-389d-43b3-a91b-b929232871eb	7229a30d-bb06-4e01-80d3-4162cabf93d9	40000	false	OP-26-93d9-000002
\.

-- Table: sale_items (1 rows)
COPY sale_items (original_price, tax_rate, promotion_id, notes, id, discount_amount, price_tier_id, cost_price, sale_id, product_id, quantity, unit_price) FROM stdin;
2000	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001 - dfsdfsd	f297a26d-7176-44ef-8c55-ec504319f357	200	\N	1000	971d5a10-8c90-47e6-810e-92a5c50b1668	80315d11-94d9-4d03-bd79-25eade94738d	1	1800
\.

-- Table: sale_payments (1 rows)
COPY sale_payments (id, sale_id, payment_method, amount, reference_number, card_last_4, notes, created_at) FROM stdin;
8af4fca4-a9c5-4090-b478-12e72f4ef2a9	971d5a10-8c90-47e6-810e-92a5c50b1668	CASH	2000				2026-04-29 11:13:03
\.

-- Table: purchase_order_items (5 rows)
COPY purchase_order_items (product_id, qty_po, qty_receive, unit_price, tax_rate, discount_rate, id, po_id) FROM stdin;
80315d11-94d9-4d03-bd79-25eade94738d	1	1	2000	0	0	d63c8923-06b1-440e-ada0-1940c0429af3	7b9a977d-e5fb-4b52-b519-651f4aaf8725
20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	3984840a-5c7e-4db9-9d00-838b87ad9e3c	a66644fa-9734-4294-ad09-dac618dc6bf9
20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	d8109b67-7e63-4912-a2ec-8410c559f270	23b83e99-bbc2-467a-af9b-85c7f95b830c
20afbb46-9d89-4087-adb2-f874552b7479	1	1	2000	0	0	4bf1b3af-7996-4c59-9a84-815a075017ed	8e897c4a-d613-49e2-96a2-842cb69c18c5
20afbb46-9d89-4087-adb2-f874552b7479	20	0	1500	0	0	526b192a-b6ee-40c9-8401-c60239d5aeaa	3dd1a94e-2ee0-496f-bf4f-038bb8d39772
\.

-- Table: purchase_return_items (11 rows)
COPY purchase_return_items (tax_rate, id, product_id, quantity, unit_price, amount, discount, return_id, po_item_id, notes) FROM stdin;
0	e52835b0-ff24-4e2b-8da2-e2ca53259f27	20afbb46-9d89-4087-adb2-f874552b7479	2	2000	4000	0	1928d830-324e-40d0-90d2-28d168d7b66f	00000000-0000-0000-0000-000000000000	
0	c45ebbac-2ed0-40a1-b845-54db4f9a3aef	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	2000	0	1e827e52-fd70-44e1-994b-09c6c0f6f235	00000000-0000-0000-0000-000000000000	
0	bbe572c8-08ba-440b-bd20-e644f405a6e3	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	2000	0	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	00000000-0000-0000-0000-000000000000	
0	5d5efc60-6a20-43fc-8741-36f11fef31b4	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	2000	0	57460918-c311-41b2-9592-d636eb4e41dd	00000000-0000-0000-0000-000000000000	
0	f7c888a6-40c9-4a71-a0bc-ee080f579bf4	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	2000	0	32200a9d-642b-4d24-86b3-4425aebb07f8	00000000-0000-0000-0000-000000000000	
0	b4436858-3198-4609-9c8a-21dd962e5f39	20afbb46-9d89-4087-adb2-f874552b7479	1	2000	2000	0	3e377261-afc7-41db-931e-e19586618b2e	00000000-0000-0000-0000-000000000000	
0	83fdc1fa-e25f-4ae4-b109-f746b2efd516	20afbb46-9d89-4087-adb2-f874552b7479	1	100	100	0	b089db6e-918c-4b41-a915-b2b70c0d528f	00000000-0000-0000-0000-000000000000	
0	8e40512b-cbdf-4043-badf-3aaef32f9ac3	20afbb46-9d89-4087-adb2-f874552b7479	1	100	100	0	ca735863-1f75-4312-8555-8e05fc1a3249	00000000-0000-0000-0000-000000000000	
0	b6541898-e4fd-4023-ba42-b5bec0e2171d	20afbb46-9d89-4087-adb2-f874552b7479	1	100	100	0	1bcf88d2-aa2f-4b92-a8af-f96204be7335	00000000-0000-0000-0000-000000000000	
0	896d041c-f665-4e7c-97b5-feefdf77ccb7	20afbb46-9d89-4087-adb2-f874552b7479	1	100	100	0	8c017509-e77e-4508-aef0-825a5f5913e5	00000000-0000-0000-0000-000000000000	
0	6dee9d1a-41cc-432a-b3b7-c10c763d4323	20afbb46-9d89-4087-adb2-f874552b7479	1	100	100	0	11204a47-3e0e-4b79-8b9e-9246163913fd	00000000-0000-0000-0000-000000000000	
\.

-- Table: cash_drawer_transactions (2 rows)
COPY cash_drawer_transactions (created_by, cash_drawer_id, amount, sale_id, payment_method, reason, created_at, id, type, balance_after) FROM stdin;
a0624492-9ab0-4dbb-8d60-a1eea1c20614	d1bb2074-55e0-47ca-9791-43b6b777e5b8	1000	\N	\N	Opening cash drawer	2026-04-29 11:12:46	b0146f36-52ec-4353-9f92-270ec52eb087	OPENING	1000
a0624492-9ab0-4dbb-8d60-a1eea1c20614	d1bb2074-55e0-47ca-9791-43b6b777e5b8	2000	971d5a10-8c90-47e6-810e-92a5c50b1668	\N	Penjualan #SLS-20260429-836	2026-04-29 11:13:03	d31b646c-7397-4f7b-9f11-da50d607ab12	CASH_IN	3000
\.

-- Table: stock_opname_items (3 rows)
COPY stock_opname_items (opname_id, product_id, system_quantity, status, cost_price, id, actual_quantity, difference, notes) FROM stdin;
b275dfbf-db21-4d95-8de3-4c3f9f948234	80315d11-94d9-4d03-bd79-25eade94738d	0	pending	1000	a779b574-7f50-445b-9196-e11dc82deab6	10	10	
6a1432fc-389d-43b3-a91b-b929232871eb	80315d11-94d9-4d03-bd79-25eade94738d	0	done	1000	e1736130-f08d-4362-b72b-35f7e9e892af	10	10	
6a1432fc-389d-43b3-a91b-b929232871eb	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	0	done	3000	6dbfff3a-05d2-48d5-b581-4aaf4188c298	10	10	
\.

-- Table: promotions (1 rows)
COPY promotions (code, discount_value, min_purchase_amount, buy_quantity, get_quantity, created_at, scope, end_time, end_date, id, name, start_date, is_active, usage_count, description, promotion_type, max_discount_amount, start_time, usage_limit) FROM stdin;
DP00001	10	0	1	1	2026-04-12 13:30:20	ALL	\N	2026-04-01 07:00:00	5936bddd-a809-41d8-9044-3d91d6a2e6f9	dfsdfsd	2026-04-01 07:00:00	true	0	testtt	PERCENTAGE	\N	\N	\N
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (min_quantity, max_quantity, unit_price, is_active, created_at, id, product_id, tier_name) FROM stdin;
3	\N	4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1
6	\N	4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2
12	\N	3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3
3	\N	1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b	80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1
3	\N	1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2
6	\N	1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1
12	\N	1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3
\.

-- Table: products (3 rows)
COPY products (name, tax_rate, reorder_point, company_id, updated_at, id, sku, description, category_id, unit_id, cost_price, status, created_at, retail_price, is_trackable, is_active, barcode) FROM stdin;
Nasi Gurame	0	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-11 08:15:37	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	200	nasi gurame enak	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	3000	active	2026-03-17 09:48:30	5000	false	true	100
Nasi Padang	0	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-13 08:04:49	80315d11-94d9-4d03-bd79-25eade94738d	201	\N	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	1000	active	2026-03-30 07:51:35	2000	false	true	101
nasi pecel	0	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-01 14:52:17	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	202	Nasi Pecel Enak	88c17a83-e2e4-40c1-8487-aaf4dec60c99	d0ee1f31-abfc-41ac-848d-d501024f55f6	200	active	2026-02-20 16:19:35	500	false	true	102
\.

-- Table: categories (4 rows)
COPY categories (name, description, parent_id, company_id, is_active, created_at, id, code) FROM stdin;
Nonfood	barang nonfood	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf
Test Kategori Baru		\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34	88c17a83-e2e4-40c1-8487-aaf4dec60c99	TEST01
Kategori Test Baru		\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-23 08:24:49	0ee6e45f-6577-4f27-bee4-5740ca57d1aa	TEST02
Minuman	daftar minuman	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm
\.

-- Table: units_of_measure (5 rows)
COPY units_of_measure (company_id, id, code, name, description, is_active, created_at) FROM stdin;
7229a30d-bb06-4e01-80d3-4162cabf93d9	80a309c7-946b-418b-8c01-e66e0a8c1722	un	Unit	sdfsdf	true	2026-04-23 08:24:29
7229a30d-bb06-4e01-80d3-4162cabf93d9	d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS	unit	true	2026-02-24 10:59:45
7229a30d-bb06-4e01-80d3-4162cabf93d9	2cf54205-b490-42d7-ad99-2311482e9b07	213	21321	2132	true	2026-02-20 16:20:08
\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece	satuan product	true	2026-03-10 12:13:39
\N	937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa	sadsad	true	2026-03-10 12:18:45
\.

