-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-04-24 11:00:00
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (id, username, email, full_name, company_id, last_login, is_active, password, role, status, created_at, updated_at, phone) FROM stdin;
a0624492-9ab0-4dbb-8d60-a1eea1c20614	kasir1	dsf@gmail.com	Kasir 1	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-24 07:06:43	true	$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	cashier	active	2026-03-27 08:50:12	2026-04-24 07:06:43	088888
583e3b50-e159-43bf-bd8d-e91b79975a0a	budifikri	fikriawan2007@gmail.com	Mochammad Budi FIkriawan	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-24 07:07:21	true	$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	admin	active	2026-02-18 11:11:38	2026-04-24 07:07:21	\N
\.

-- Table: warehouses (2 rows)
COPY warehouses (updated_at, id, code, type, address, manager_id, is_active, name, status, city, phone, company_id, created_at) FROM stdin;
2026-03-03 20:16:10	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	TK	MAIN	123 Test Street, Test City	\N	true	TOKO123	active	Test City	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-19 17:33:22
2026-03-10 20:48:20	7faf63da-41f0-465e-ad68-48d40b6a135f	WH2-20260305T07203	BRANCH	456 Transfer Street	\N	false	Second Warehouse 20260305T07203	inactive	Transfer City	+1234567890	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-05 14:20:37
\.

-- Table: customers (1 rows)
COPY customers (status, loyalty_points, bank_account_name, name, phone, tier, credit_limit, lastPurchaseDate, bank_branch, updated_at, id, customer_code, address, city, credit_balance, total_purchases, bank_account_number, created_at, email, company_id, bank_name, is_active) FROM stdin;
active	0		were	ewr	BRONZE	0	\N		2026-04-23 07:43:12	b129a403-17d5-491c-95e0-2b8165f3d237	CUST-20260423T00425	ewrew	ewr	0	0		2026-04-23 07:42:53	were	7229a30d-bb06-4e01-80d3-4162cabf93d9		true
\.

-- Table: suppliers (3 rows)
COPY suppliers (city, payment_terms, credit_limit, created_at, is_active, company_id, contact_person, email, phone, notes, updated_at, id, code, name, address, tax_id, status) FROM stdin;
Supplier City	NET_30	10000	2026-03-03 14:06:24	true	7229a30d-bb06-4e01-80d3-4162cabf93d9	John Doe	supplier_20260303T07062@example.com	+1234567890	Test supplier created via API	2026-03-03 14:06:24	474a9674-122b-4f92-b6ab-7f9c683b2063	SUP-1772521584647	Test Supplier 20260303T07062	123 Supplier Street	TAX-20260303T07062	active
Supplier City	NET_30	10000	2026-03-03 14:43:19	false	7229a30d-bb06-4e01-80d3-4162cabf93d9	John Doe	supplier_20260303T07431@example.com	+1234567890	Test supplier created via API	2026-03-03 20:07:58	53412491-3ae7-48f9-ada7-3a68d65bf5f0	SUP-1772523799582	Test Supplier 20260303T07431	123 Supplier Street	TAX-20260303T07431	inactive
sddfdsf	NET_30	0	2026-02-20 15:03:19	true	7229a30d-bb06-4e01-80d3-4162cabf93d9	dfd	fdf@gfg	fdf	\N	2026-03-03 20:10:25	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	SUP-1771574599094	testt	dfgdfg	dsf	active
\.

-- Table: sales (1 rows)
COPY sales (sale_number, status, discount_amount, loyalty_points_redeemed, notes, created_at, id, warehouse_id, customer_id, cash_drawer_id, sale_date, tax_amount, total_amount, change_amount, cashier_id, subtotal, paid_amount, loyalty_points_earned, updated_at, company_id) FROM stdin;
SLS-20260424-887	DONE	4000	0		2026-04-24 07:07:03	30168143-ab1b-49ae-8415-9202850c4c3c	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	\N	6b9a66f9-1479-4e46-a495-8ad9184d6afa	2026-04-24 07:07:03	0	36000	4000	a0624492-9ab0-4dbb-8d60-a1eea1c20614	36000	40000	3	2026-04-24 07:07:03	7229a30d-bb06-4e01-80d3-4162cabf93d9
\.

-- Table: purchase_orders (3 rows)
COPY purchase_orders (discount_amount, supplier_id, order_date, status_po, note_receive, updated_at, po_number, payment_terms, subtotal, total_amount, created_at, receive_date, receive_number, id, warehouse_id, status_receive, tax_amount, notes, created_by, expected_delivery, company_id, approved_by) FROM stdin;
0	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 06:57:23	APPROVE	COMPLETE	2026-04-24 06:58:15	PO-26-93D9-000001	NET_30	420000	420000	2026-04-24 06:57:23	2026-04-24 07:00:00	\N	2c2d6f41-802b-432a-8221-314226074ea9	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	receive	0		583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-24 06:57:23	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N
0	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 07:03:04	APPROVE	COMPLETE	2026-04-24 07:05:47	PO-26-93D9-000002	NET_30	200000	200000	2026-04-24 07:03:04	2026-04-24 07:00:00	\N	344113bf-22c1-416d-b76f-04656cd5cb05	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	receive	0		583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-24 07:03:04	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N
0	474a9674-122b-4f92-b6ab-7f9c683b2063	2026-04-24 07:00:00	VOID	\N	2026-04-24 10:19:52	PO-26-93D9-000003	NET_30	200000	200000	2026-04-24 10:06:24	\N	\N	5239eb24-6003-47a2-b0c3-f4f9190d5e27	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	DRAFT	0		583e3b50-e159-43bf-bd8d-e91b79975a0a	2026-04-24 07:00:00	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N
\.

-- Table: cash_drawers (1 rows)
COPY cash_drawers (drawer_number, warehouse_id, cashier_id, closing_balance, closed_at, company_id, status, opened_at, deposit_invoice_id, created_at, updated_at, opening_balance, expected_balance, variance, notes, id) FROM stdin;
CD-1776989210284	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	a0624492-9ab0-4dbb-8d60-a1eea1c20614	\N	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	OPEN	2026-04-24 07:06:50	\N	2026-04-24 07:06:50	2026-04-24 07:07:03	200000	240000	\N		6b9a66f9-1479-4e46-a495-8ad9184d6afa
\.

-- Table: sale_items (1 rows)
COPY sale_items (notes, id, quantity, original_price, discount_amount, tax_rate, sale_id, product_id, unit_price, price_tier_id, promotion_id) FROM stdin;
DP00001 - dfsdfsd	fc415e48-30a5-408b-bc06-54a9a57331f1	20	2000	200	0	30168143-ab1b-49ae-8415-9202850c4c3c	80315d11-94d9-4d03-bd79-25eade94738d	1800	\N	5936bddd-a809-41d8-9044-3d91d6a2e6f9
\.

-- Table: sale_payments (1 rows)
COPY sale_payments (sale_id, payment_method, amount, reference_number, card_last_4, notes, created_at, id) FROM stdin;
30168143-ab1b-49ae-8415-9202850c4c3c	CASH	40000				2026-04-24 07:07:03	2078af9a-9f7c-45aa-a77a-4a3b4c307162
\.

-- Table: purchase_order_items (9 rows)
COPY purchase_order_items (unit_price, tax_rate, discount_rate, id, po_id, product_id, qty_po, qty_receive) FROM stdin;
3000	0	0	0628622f-ef54-4760-b25b-43adbb9ae1e2	2c2d6f41-802b-432a-8221-314226074ea9	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	100	100
1000	0	0	6c36e9e9-6ebf-4421-862b-ee8e5ff3c82c	2c2d6f41-802b-432a-8221-314226074ea9	80315d11-94d9-4d03-bd79-25eade94738d	100	100
200	0	0	93bba8aa-553a-4bb8-8be8-564fedaa5709	2c2d6f41-802b-432a-8221-314226074ea9	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	100	100
1000	0	0	f54e55ca-54b3-4287-b9c9-9287eba2c6ac	344113bf-22c1-416d-b76f-04656cd5cb05	80315d11-94d9-4d03-bd79-25eade94738d	200	200
1000	0	0	ee3e88d6-4d99-44c8-bf6f-ca6470ccd386	5239eb24-6003-47a2-b0c3-f4f9190d5e27	80315d11-94d9-4d03-bd79-25eade94738d	200	0
2000	0	0	3984840a-5c7e-4db9-9d00-838b87ad9e3c	a66644fa-9734-4294-ad09-dac618dc6bf9	20afbb46-9d89-4087-adb2-f874552b7479	1	1
2000	0	0	d8109b67-7e63-4912-a2ec-8410c559f270	23b83e99-bbc2-467a-af9b-85c7f95b830c	20afbb46-9d89-4087-adb2-f874552b7479	1	1
2000	0	0	4bf1b3af-7996-4c59-9a84-815a075017ed	8e897c4a-d613-49e2-96a2-842cb69c18c5	20afbb46-9d89-4087-adb2-f874552b7479	1	1
1500	0	0	526b192a-b6ee-40c9-8401-c60239d5aeaa	3dd1a94e-2ee0-496f-bf4f-038bb8d39772	20afbb46-9d89-4087-adb2-f874552b7479	20	0
\.

-- Table: purchase_return_items (11 rows)
COPY purchase_return_items (product_id, quantity, unit_price, id, return_id, po_item_id, amount, notes, discount, tax_rate) FROM stdin;
20afbb46-9d89-4087-adb2-f874552b7479	2	2000	e52835b0-ff24-4e2b-8da2-e2ca53259f27	1928d830-324e-40d0-90d2-28d168d7b66f	00000000-0000-0000-0000-000000000000	4000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	2000	c45ebbac-2ed0-40a1-b845-54db4f9a3aef	1e827e52-fd70-44e1-994b-09c6c0f6f235	00000000-0000-0000-0000-000000000000	2000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	2000	bbe572c8-08ba-440b-bd20-e644f405a6e3	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	00000000-0000-0000-0000-000000000000	2000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	2000	5d5efc60-6a20-43fc-8741-36f11fef31b4	57460918-c311-41b2-9592-d636eb4e41dd	00000000-0000-0000-0000-000000000000	2000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	2000	f7c888a6-40c9-4a71-a0bc-ee080f579bf4	32200a9d-642b-4d24-86b3-4425aebb07f8	00000000-0000-0000-0000-000000000000	2000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	2000	b4436858-3198-4609-9c8a-21dd962e5f39	3e377261-afc7-41db-931e-e19586618b2e	00000000-0000-0000-0000-000000000000	2000		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	100	83fdc1fa-e25f-4ae4-b109-f746b2efd516	b089db6e-918c-4b41-a915-b2b70c0d528f	00000000-0000-0000-0000-000000000000	100		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	100	8e40512b-cbdf-4043-badf-3aaef32f9ac3	ca735863-1f75-4312-8555-8e05fc1a3249	00000000-0000-0000-0000-000000000000	100		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	100	b6541898-e4fd-4023-ba42-b5bec0e2171d	1bcf88d2-aa2f-4b92-a8af-f96204be7335	00000000-0000-0000-0000-000000000000	100		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	100	896d041c-f665-4e7c-97b5-feefdf77ccb7	8c017509-e77e-4508-aef0-825a5f5913e5	00000000-0000-0000-0000-000000000000	100		0	0
20afbb46-9d89-4087-adb2-f874552b7479	1	100	6dee9d1a-41cc-432a-b3b7-c10c763d4323	11204a47-3e0e-4b79-8b9e-9246163913fd	00000000-0000-0000-0000-000000000000	100		0	0
\.

-- Table: cash_drawer_transactions (2 rows)
COPY cash_drawer_transactions (created_at, created_by, id, type, amount, reason, cash_drawer_id, balance_after, sale_id, payment_method) FROM stdin;
2026-04-24 07:06:50	a0624492-9ab0-4dbb-8d60-a1eea1c20614	0238030f-6162-4064-b3ea-6f0499e208f8	OPENING	200000	Opening cash drawer	6b9a66f9-1479-4e46-a495-8ad9184d6afa	200000	\N	\N
2026-04-24 07:07:03	a0624492-9ab0-4dbb-8d60-a1eea1c20614	87ccbfb5-8031-4722-91b2-5b7a2e2c4c20	CASH_IN	40000	Penjualan #SLS-20260424-887	6b9a66f9-1479-4e46-a495-8ad9184d6afa	240000	30168143-ab1b-49ae-8415-9202850c4c3c	\N
\.

-- Table: promotions (1 rows)
COPY promotions (name, get_quantity, start_date, is_active, description, max_discount_amount, buy_quantity, usage_count, created_at, id, scope, discount_value, min_purchase_amount, end_date, usage_limit, code, promotion_type, start_time, end_time) FROM stdin;
dfsdfsd	1	2026-04-01 07:00:00	true	testtt	\N	1	0	2026-04-12 13:30:20	5936bddd-a809-41d8-9044-3d91d6a2e6f9	ALL	10	0	2026-04-01 07:00:00	\N	DP00001	PERCENTAGE	\N	\N
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (product_id, tier_name, min_quantity, max_quantity, unit_price, is_active, created_at, id) FROM stdin;
b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1	3	\N	4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8
b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2	6	\N	4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3
b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3	12	\N	3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a
80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1	3	\N	1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b
20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2	3	\N	1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7
20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1	6	\N	1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d
20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3	12	\N	1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba
\.

-- Table: products (3 rows)
COPY products (updated_at, reorder_point, company_id, description, unit_id, retail_price, is_active, barcode, is_trackable, created_at, tax_rate, id, sku, name, category_id, status, cost_price) FROM stdin;
2026-04-11 08:15:37	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	nasi gurame enak	d0ee1f31-abfc-41ac-848d-d501024f55f6	5000	true	100	false	2026-03-17 09:48:30	0	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	200	Nasi Gurame	88c17a83-e2e4-40c1-8487-aaf4dec60c99	active	3000
2026-04-13 08:04:49	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N	d0ee1f31-abfc-41ac-848d-d501024f55f6	2000	true	101	false	2026-03-30 07:51:35	0	80315d11-94d9-4d03-bd79-25eade94738d	201	Nasi Padang	88c17a83-e2e4-40c1-8487-aaf4dec60c99	active	1000
2026-04-01 14:52:17	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	Nasi Pecel Enak	d0ee1f31-abfc-41ac-848d-d501024f55f6	500	true	102	false	2026-02-20 16:19:35	0	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	202	nasi pecel	88c17a83-e2e4-40c1-8487-aaf4dec60c99	active	200
\.

-- Table: categories (4 rows)
COPY categories (company_id, is_active, created_at, id, code, name, description, parent_id) FROM stdin;
7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf	Nonfood	barang nonfood	\N
7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34	88c17a83-e2e4-40c1-8487-aaf4dec60c99	TEST01	Test Kategori Baru		\N
7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-23 08:24:49	0ee6e45f-6577-4f27-bee4-5740ca57d1aa	TEST02	Kategori Test Baru		\N
7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm	Minuman	daftar minuman	\N
\.

-- Table: units_of_measure (5 rows)
COPY units_of_measure (description, is_active, created_at, company_id, id, code, name) FROM stdin;
sdfsdf	true	2026-04-23 08:24:29	7229a30d-bb06-4e01-80d3-4162cabf93d9	80a309c7-946b-418b-8c01-e66e0a8c1722	un	Unit
unit	true	2026-02-24 10:59:45	7229a30d-bb06-4e01-80d3-4162cabf93d9	d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS
2132	true	2026-02-20 16:20:08	7229a30d-bb06-4e01-80d3-4162cabf93d9	2cf54205-b490-42d7-ad99-2311482e9b07	213	21321
satuan product	true	2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece
sadsad	true	2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa
\.

