-- PostgreSQL Backup
-- Company: comp-2026023i (ID: 7229a30d-bb06-4e01-80d3-4162cabf93d9)
-- Backup Date: 2026-05-01 11:20:05
-- Generated by POS Retail System

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_min_messages = warning;
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';

-- Table: users (2 rows)
COPY users (role, is_active, phone, username, password, status, company_id, created_at, updated_at, last_login, id, email, full_name) FROM stdin;
cashier	true	088888	kasir1	$2a$10$btSKL6A8iYKJo8Jqs4dJHO7t9C8Chfitzlee5IoyUjm4TL7yVpUra	active	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-03-27 08:50:12	2026-04-29 11:12:41	2026-04-29 11:12:41	a0624492-9ab0-4dbb-8d60-a1eea1c20614	dsf@gmail.com	Kasir 1
admin	true	\N	budifikri	$2a$10$UD7QtFmZCeHecha5FOfkRuEucEa.jJM73rpg7OBA6XqcSLWsQA2FW	active	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-02-18 11:11:38	2026-04-30 06:58:15	2026-04-30 06:58:15	583e3b50-e159-43bf-bd8d-e91b79975a0a	fikriawan2007@gmail.com	Mochammad Budi FIkriawan
\.

-- Table: warehouses (2 rows)
COPY warehouses (city, phone, manager_id, company_id, is_active, id, code, name, type, status, created_at, updated_at, address) FROM stdin;
Test City	+1234567890	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	TK	TOKO123	MAIN	active	2026-02-19 17:33:22	2026-03-03 20:16:10	123 Test Street, Test City
Transfer City	+1234567890	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	false	7faf63da-41f0-465e-ad68-48d40b6a135f	WH2-20260305T07203	Second Warehouse 20260305T07203	BRANCH	inactive	2026-03-05 14:20:37	2026-03-10 20:48:20	456 Transfer Street
\.

-- Table: customers (1 rows)
COPY customers (email, address, total_purchases, bank_account_name, name, phone, city, status, loyalty_points, credit_limit, credit_balance, lastPurchaseDate, company_id, bank_name, bank_account_number, bank_branch, created_at, is_active, customer_code, tier, updated_at, id) FROM stdin;
were	ewrew	0		were	ewr	ewr	active	0	0	0	\N	7229a30d-bb06-4e01-80d3-4162cabf93d9				2026-04-23 07:42:53	true	CUST-20260423T00425	BRONZE	2026-04-23 07:43:12	b129a403-17d5-491c-95e0-2b8165f3d237
\.

-- Table: suppliers (3 rows)
COPY suppliers (id, code, name, status, address, city, created_at, email, phone, payment_terms, credit_limit, updated_at, contact_person, tax_id, company_id, notes, is_active) FROM stdin;
474a9674-122b-4f92-b6ab-7f9c683b2063	SUP-1772521584647	Test Supplier 20260303T07062	active	123 Supplier Street	Supplier City	2026-03-03 14:06:24	supplier_20260303T07062@example.com	+1234567890	NET_30	10000	2026-03-03 14:06:24	John Doe	TAX-20260303T07062	7229a30d-bb06-4e01-80d3-4162cabf93d9	Test supplier created via API	true
53412491-3ae7-48f9-ada7-3a68d65bf5f0	SUP-1772523799582	Test Supplier 20260303T07431	inactive	123 Supplier Street	Supplier City	2026-03-03 14:43:19	supplier_20260303T07431@example.com	+1234567890	NET_30	10000	2026-03-03 20:07:58	John Doe	TAX-20260303T07431	7229a30d-bb06-4e01-80d3-4162cabf93d9	Test supplier created via API	false
57658cd5-f6df-4f22-80bd-a070fc1fa4a8	SUP-1771574599094	testt	active	dfgdfg	sddfdsf	2026-02-20 15:03:19	fdf@gfg	fdf	NET_30	0	2026-03-03 20:10:25	dfd	dsf	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N	true
\.

-- Table: sales (1 rows)
COPY sales (customer_id, loyalty_points_redeemed, id, cashier_id, cash_drawer_id, discount_amount, change_amount, sale_number, warehouse_id, company_id, sale_date, tax_amount, loyalty_points_earned, updated_at, status, subtotal, total_amount, paid_amount, notes, created_at) FROM stdin;
\N	0	971d5a10-8c90-47e6-810e-92a5c50b1668	a0624492-9ab0-4dbb-8d60-a1eea1c20614	d1bb2074-55e0-47ca-9791-43b6b777e5b8	200	200	SLS-20260429-836	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	7229a30d-bb06-4e01-80d3-4162cabf93d9	2026-04-29 11:13:03	0	0	2026-04-29 11:13:03	DONE	1800	1800	2000		2026-04-29 11:13:03
\.

-- Table: purchase_orders (1 rows)
COPY purchase_orders (warehouse_id, order_date, note_receive, total_amount, notes, created_by, tax_amount, company_id, approved_by, updated_at, receive_number, supplier_id, created_at, receive_date, expected_delivery, payment_terms, status_po, status_receive, subtotal, discount_amount, id, po_number) FROM stdin;
ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 07:00:00	COMPLETE	2000		583e3b50-e159-43bf-bd8d-e91b79975a0a	0	7229a30d-bb06-4e01-80d3-4162cabf93d9	\N	2026-04-29 11:12:03	\N	57658cd5-f6df-4f22-80bd-a070fc1fa4a8	2026-04-29 11:11:28	2026-04-29 07:00:00	2026-04-29 07:00:00	NET_30	APPROVE	receive	2000	0	7b9a977d-e5fb-4b52-b519-651f4aaf8725	PO-26-93D9-000001
\.

-- Table: cash_drawers (1 rows)
COPY cash_drawers (id, drawer_number, expected_balance, variance, opened_at, closed_at, status, opening_balance, deposit_invoice_id, warehouse_id, closing_balance, notes, created_at, updated_at, cashier_id, company_id) FROM stdin;
d1bb2074-55e0-47ca-9791-43b6b777e5b8	CD-1777435966270	3000	\N	2026-04-29 11:12:46	\N	OPEN	1000	\N	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	\N		2026-04-29 11:12:46	2026-04-29 11:13:03	a0624492-9ab0-4dbb-8d60-a1eea1c20614	7229a30d-bb06-4e01-80d3-4162cabf93d9
\.

-- Table: stock_opnames (2 rows)
COPY stock_opnames (opname_number, user_id, status, notes, updated_at, id, warehouse_id, opname_date, created_at, company_id, total_selisih) FROM stdin;
OP-26-93d9-000001	583e3b50-e159-43bf-bd8d-e91b79975a0a	draft		2026-04-29 11:15:02	b275dfbf-db21-4d95-8de3-4c3f9f948234	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 07:00:00	2026-04-29 11:15:02	7229a30d-bb06-4e01-80d3-4162cabf93d9	0
OP-26-93d9-000002	583e3b50-e159-43bf-bd8d-e91b79975a0a	approved		2026-04-29 17:05:44	6a1432fc-389d-43b3-a91b-b929232871eb	ba5226d8-4b25-4a2b-ac61-ab90c495f8bd	2026-04-29 07:00:00	2026-04-29 11:54:48	7229a30d-bb06-4e01-80d3-4162cabf93d9	40000
\.

-- Table: sale_items (1 rows)
COPY sale_items (product_id, quantity, unit_price, tax_rate, promotion_id, notes, cost_price, id, sale_id, original_price, discount_amount, price_tier_id) FROM stdin;
80315d11-94d9-4d03-bd79-25eade94738d	1	1800	0	5936bddd-a809-41d8-9044-3d91d6a2e6f9	DP00001 - dfsdfsd	1000	f297a26d-7176-44ef-8c55-ec504319f357	971d5a10-8c90-47e6-810e-92a5c50b1668	2000	200	\N
\.

-- Table: sale_payments (1 rows)
COPY sale_payments (created_at, id, sale_id, payment_method, amount, reference_number, card_last_4, notes) FROM stdin;
2026-04-29 11:13:03	8af4fca4-a9c5-4090-b478-12e72f4ef2a9	971d5a10-8c90-47e6-810e-92a5c50b1668	CASH	2000			
\.

-- Table: purchase_order_items (5 rows)
COPY purchase_order_items (qty_po, qty_receive, unit_price, tax_rate, discount_rate, id, po_id, product_id) FROM stdin;
1	1	2000	0	0	d63c8923-06b1-440e-ada0-1940c0429af3	7b9a977d-e5fb-4b52-b519-651f4aaf8725	80315d11-94d9-4d03-bd79-25eade94738d
1	1	2000	0	0	3984840a-5c7e-4db9-9d00-838b87ad9e3c	a66644fa-9734-4294-ad09-dac618dc6bf9	20afbb46-9d89-4087-adb2-f874552b7479
1	1	2000	0	0	d8109b67-7e63-4912-a2ec-8410c559f270	23b83e99-bbc2-467a-af9b-85c7f95b830c	20afbb46-9d89-4087-adb2-f874552b7479
1	1	2000	0	0	4bf1b3af-7996-4c59-9a84-815a075017ed	8e897c4a-d613-49e2-96a2-842cb69c18c5	20afbb46-9d89-4087-adb2-f874552b7479
20	0	1500	0	0	526b192a-b6ee-40c9-8401-c60239d5aeaa	3dd1a94e-2ee0-496f-bf4f-038bb8d39772	20afbb46-9d89-4087-adb2-f874552b7479
\.

-- Table: purchase_return_items (11 rows)
COPY purchase_return_items (id, po_item_id, product_id, quantity, return_id, unit_price, amount, notes, discount, tax_rate) FROM stdin;
e52835b0-ff24-4e2b-8da2-e2ca53259f27	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	2	1928d830-324e-40d0-90d2-28d168d7b66f	2000	4000		0	0
c45ebbac-2ed0-40a1-b845-54db4f9a3aef	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	1e827e52-fd70-44e1-994b-09c6c0f6f235	2000	2000		0	0
bbe572c8-08ba-440b-bd20-e644f405a6e3	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	7ca3a40d-056e-4b92-8426-9a4e5ac79d6d	2000	2000		0	0
5d5efc60-6a20-43fc-8741-36f11fef31b4	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	57460918-c311-41b2-9592-d636eb4e41dd	2000	2000		0	0
f7c888a6-40c9-4a71-a0bc-ee080f579bf4	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	32200a9d-642b-4d24-86b3-4425aebb07f8	2000	2000		0	0
b4436858-3198-4609-9c8a-21dd962e5f39	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	3e377261-afc7-41db-931e-e19586618b2e	2000	2000		0	0
83fdc1fa-e25f-4ae4-b109-f746b2efd516	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	b089db6e-918c-4b41-a915-b2b70c0d528f	100	100		0	0
8e40512b-cbdf-4043-badf-3aaef32f9ac3	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	ca735863-1f75-4312-8555-8e05fc1a3249	100	100		0	0
b6541898-e4fd-4023-ba42-b5bec0e2171d	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	1bcf88d2-aa2f-4b92-a8af-f96204be7335	100	100		0	0
896d041c-f665-4e7c-97b5-feefdf77ccb7	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	8c017509-e77e-4508-aef0-825a5f5913e5	100	100		0	0
6dee9d1a-41cc-432a-b3b7-c10c763d4323	00000000-0000-0000-0000-000000000000	20afbb46-9d89-4087-adb2-f874552b7479	1	11204a47-3e0e-4b79-8b9e-9246163913fd	100	100		0	0
\.

-- Table: cash_drawer_transactions (2 rows)
COPY cash_drawer_transactions (created_at, created_by, amount, reason, id, cash_drawer_id, type, balance_after, sale_id, payment_method) FROM stdin;
2026-04-29 11:12:46	a0624492-9ab0-4dbb-8d60-a1eea1c20614	1000	Opening cash drawer	b0146f36-52ec-4353-9f92-270ec52eb087	d1bb2074-55e0-47ca-9791-43b6b777e5b8	OPENING	1000	\N	\N
2026-04-29 11:13:03	a0624492-9ab0-4dbb-8d60-a1eea1c20614	2000	Penjualan #SLS-20260429-836	d31b646c-7397-4f7b-9f11-da50d607ab12	d1bb2074-55e0-47ca-9791-43b6b777e5b8	CASH_IN	3000	971d5a10-8c90-47e6-810e-92a5c50b1668	\N
\.

-- Table: stock_opname_items (3 rows)
COPY stock_opname_items (id, opname_id, product_id, system_quantity, actual_quantity, difference, notes, cost_price, status) FROM stdin;
a779b574-7f50-445b-9196-e11dc82deab6	b275dfbf-db21-4d95-8de3-4c3f9f948234	80315d11-94d9-4d03-bd79-25eade94738d	0	10	10		1000	pending
e1736130-f08d-4362-b72b-35f7e9e892af	6a1432fc-389d-43b3-a91b-b929232871eb	80315d11-94d9-4d03-bd79-25eade94738d	0	10	10		1000	done
6dbfff3a-05d2-48d5-b581-4aaf4188c298	6a1432fc-389d-43b3-a91b-b929232871eb	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	0	10	10		3000	done
\.

-- Table: promotions (1 rows)
COPY promotions (scope, buy_quantity, get_quantity, start_time, end_date, usage_limit, usage_count, created_at, id, discount_value, min_purchase_amount, is_active, name, description, max_discount_amount, start_date, end_time, code, promotion_type) FROM stdin;
ALL	1	1	\N	2026-04-01 07:00:00	\N	0	2026-04-12 13:30:20	5936bddd-a809-41d8-9044-3d91d6a2e6f9	10	0	true	dfsdfsd	testtt	\N	2026-04-01 07:00:00	\N	DP00001	PERCENTAGE
\.

-- Table: price_tiers (7 rows)
COPY price_tiers (max_quantity, unit_price, is_active, created_at, id, product_id, tier_name, min_quantity) FROM stdin;
\N	4500	true	2026-04-11 08:15:37	5e815082-e020-4ffe-a72e-2dd2c3abdea8	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 1	3
\N	4000	true	2026-04-11 08:15:37	41d6823c-72bd-4c45-aa8f-8d42fb6620e3	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 2	6
\N	3500	true	2026-04-11 08:15:37	49b295c7-0c19-4008-ab3f-2db996a73a5a	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	Grosir 3	12
\N	1900	true	2026-04-13 08:04:49	fb8f25be-4455-4d8f-968e-168a0d73120b	80315d11-94d9-4d03-bd79-25eade94738d	Grosir 1	3
\N	1900	true	2026-04-09 17:27:13	fc6db036-972b-4660-b6fe-569ac8bf6ce7	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 2	3
\N	1700	true	2026-04-09 17:27:13	020f8d94-8427-40dd-9f9f-9b8c7098146d	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 1	6
\N	1600	true	2026-04-09 17:27:13	fc242980-a53c-4e6b-a5f5-f1b00e48eaba	20afbb46-9d89-4087-adb2-f874552b7479	Grosir 3	12
\.

-- Table: products (3 rows)
COPY products (tax_rate, cost_price, company_id, reorder_point, sku, name, description, unit_id, barcode, category_id, is_trackable, created_at, updated_at, is_active, id, retail_price, status) FROM stdin;
0	3000	7229a30d-bb06-4e01-80d3-4162cabf93d9	0	200	Nasi Gurame	nasi gurame enak	d0ee1f31-abfc-41ac-848d-d501024f55f6	100	88c17a83-e2e4-40c1-8487-aaf4dec60c99	false	2026-03-17 09:48:30	2026-04-11 08:15:37	true	b7ac25a2-3d8b-479d-83d9-ff8ddefb265c	5000	active
0	1000	7229a30d-bb06-4e01-80d3-4162cabf93d9	0	201	Nasi Padang	\N	d0ee1f31-abfc-41ac-848d-d501024f55f6	101	88c17a83-e2e4-40c1-8487-aaf4dec60c99	false	2026-03-30 07:51:35	2026-04-13 08:04:49	true	80315d11-94d9-4d03-bd79-25eade94738d	2000	active
0	200	7229a30d-bb06-4e01-80d3-4162cabf93d9	0	202	nasi pecel	Nasi Pecel Enak	d0ee1f31-abfc-41ac-848d-d501024f55f6	102	88c17a83-e2e4-40c1-8487-aaf4dec60c99	false	2026-02-20 16:19:35	2026-04-01 14:52:17	true	6d79a8bf-30c9-4730-9727-1e07ab5c93bd	500	active
\.

-- Table: categories (4 rows)
COPY categories (parent_id, company_id, is_active, created_at, id, code, name, description) FROM stdin;
\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	98a0ffbb-2c60-4b3b-b61f-8516dd57e73d	nf	Nonfood	barang nonfood
\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-03-10 20:39:34	88c17a83-e2e4-40c1-8487-aaf4dec60c99	TEST01	Test Kategori Baru	
\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-23 08:24:49	0ee6e45f-6577-4f27-bee4-5740ca57d1aa	TEST02	Kategori Test Baru	
\N	7229a30d-bb06-4e01-80d3-4162cabf93d9	true	2026-04-11 14:43:19	f9aa5d58-5aef-4f8b-a279-a463a422b38b	mnm	Minuman	daftar minuman
\.

-- Table: units_of_measure (5 rows)
COPY units_of_measure (description, is_active, created_at, company_id, id, code, name) FROM stdin;
sdfsdf	true	2026-04-23 08:24:29	7229a30d-bb06-4e01-80d3-4162cabf93d9	80a309c7-946b-418b-8c01-e66e0a8c1722	un	Unit
unit	true	2026-02-24 10:59:45	7229a30d-bb06-4e01-80d3-4162cabf93d9	d0ee1f31-abfc-41ac-848d-d501024f55f6	pcs	PCS
2132	true	2026-02-20 16:20:08	7229a30d-bb06-4e01-80d3-4162cabf93d9	2cf54205-b490-42d7-ad99-2311482e9b07	213	21321
satuan product	true	2026-03-10 12:13:39	\N	6beb083e-f892-4b69-b7b0-dc6be61ab65b	pc	Piece
sadsad	true	2026-03-10 12:18:45	\N	937e180b-a935-46eb-98c5-fabe06107db3	sad	sadsa
\.

