package services

import (
	"bufio"
	"bytes"
	"encoding/csv"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/pos-retail/go_backend/internal/config"
	"github.com/pos-retail/go_backend/internal/models"
	"github.com/pos-retail/go_backend/internal/repository"
	"github.com/robfig/cron/v3"
	"gorm.io/gorm"
)

type BackupService struct {
	db           *gorm.DB
	repo         *repository.BackupRepository
	backupDir    string
	pgDumpPath   string
	dbConfig     config.DatabaseConfig
	cron         *cron.Cron
	companyCrons map[uuid.UUID]cron.EntryID
}

func NewBackupService(db *gorm.DB, repo *repository.BackupRepository, cfg *config.Config) *BackupService {
	backupDir := cfg.Backup.Path
	if backupDir == "" {
		backupDir = "./backups"
	}

	pgDumpPath := cfg.Backup.PgDumpPath
	if pgDumpPath == "" {
		pgDumpPath = "pg_dump"
	}

	svc := &BackupService{
		db:           db,
		repo:         repo,
		backupDir:    backupDir,
		pgDumpPath:   pgDumpPath,
		dbConfig:     cfg.Database,
		cron:         cron.New(),
		companyCrons: make(map[uuid.UUID]cron.EntryID),
	}

	svc.ensureBackupDir()
	return svc
}

func (s *BackupService) ensureBackupDir() {
	os.MkdirAll(s.backupDir, 0755)
}

type TableInfo struct {
	Name     string
	RowCount int64
}

var companyTables = []string{
	"users",
	"warehouses",
	"customers",
	"suppliers",
	"sales",
	"purchase_orders",
	"purchase_returns",
	"invoices_incoming",
	"invoices_outgoing",
	"cash_drawers",
	"stock_opnames",
}

var childTables = []string{
	"sale_items",
	"sale_payments",
	"purchase_order_items",
	"purchase_return_items",
	"invoice_items",
	"invoice_payments",
	"cash_drawer_transactions",
	"stock_opname_items",
	"sales_returns",
	"sales_return_items",
	"item_exchanges",
	"exchange_items",
	"promotions",
	"promotion_products",
	"promotion_categories",
	"promotion_customers",
	"price_tiers",
}

var sharedTables = []string{
	"products",
	"categories",
	"units_of_measure",
}

var masterTables = []string{
	"users",
	"warehouses",
	"customers",
	"suppliers",
	"products",
	"categories",
	"units_of_measure",
	"promotions",
	"promotion_products",
	"promotion_categories",
	"promotion_customers",
	"price_tiers",
}

var transactionTables = []string{
	"sales",
	"sale_items",
	"sale_payments",
	"purchase_orders",
	"purchase_order_items",
	"purchase_returns",
	"purchase_return_items",
	"invoices_incoming",
	"invoices_outgoing",
	"invoice_items",
	"invoice_payments",
	"cash_drawers",
	"cash_drawer_transactions",
	"stock_opnames",
	"stock_opname_items",
	"item_exchanges",
	"exchange_items",
	"sales_returns",
	"sales_return_items",
}

func (s *BackupService) CreateBackup(companyID uuid.UUID, companyCode, userID string, isAuto bool) (*models.BackupLog, error) {
	startTime := time.Now()

	if strings.TrimSpace(companyCode) == "" {
		companyCode = s.getCompanyCode(companyID)
	}
	if strings.TrimSpace(companyCode) == "" {
		companyCode = companyID.String()[:8]
	}
	companyCode = strings.ToLower(strings.TrimSpace(companyCode))

	companyDir := filepath.Join(s.backupDir, strings.ToLower(companyCode))
	os.MkdirAll(companyDir, 0755)

	timestamp := time.Now().Format("20060102_150405")
	filename := fmt.Sprintf("%s_%s.sql", strings.ToLower(companyCode), timestamp)
	filePath := filepath.Join(companyDir, filename)

	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("-- PostgreSQL Backup\n"))
	buf.WriteString(fmt.Sprintf("-- Company: %s (ID: %s)\n", companyCode, companyID.String()))
	buf.WriteString(fmt.Sprintf("-- Backup Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	buf.WriteString(fmt.Sprintf("-- Generated by POS Retail System\n\n"))

	buf.WriteString("SET statement_timeout = 0;\n")
	buf.WriteString("SET lock_timeout = 0;\n")
	buf.WriteString("SET client_min_messages = warning;\n")
	buf.WriteString("SET default_transaction_read_only = off;\n")
	buf.WriteString("SET client_encoding = 'UTF8';\n\n")

	tableCount := 0
	totalRows := int64(0)

	for _, tableName := range companyTables {
		rows, err := s.dumpTable(&buf, tableName, companyID, true, false)
		if err != nil {
			return nil, fmt.Errorf("error dumping table %s: %w", tableName, err)
		}
		if rows > 0 {
			tableCount++
			totalRows += rows
		}
	}

	for _, tableName := range childTables {
		rows, err := s.dumpTable(&buf, tableName, companyID, false, true)
		if err != nil {
			return nil, fmt.Errorf("error dumping table %s: %w", tableName, err)
		}
		if rows > 0 {
			tableCount++
			totalRows += rows
		}
	}

	for _, tableName := range sharedTables {
		rows, err := s.dumpTable(&buf, tableName, companyID, false, false)
		if err != nil {
			return nil, fmt.Errorf("error dumping table %s: %w", tableName, err)
		}
		if rows > 0 {
			tableCount++
			totalRows += rows
		}
	}

	err := os.WriteFile(filePath, buf.Bytes(), 0644)
	if err != nil {
		return nil, fmt.Errorf("error writing backup file: %w", err)
	}

	fileInfo, err := os.Stat(filePath)
	if err != nil {
		return nil, fmt.Errorf("error getting file info: %w", err)
	}

	backupLog := &models.BackupLog{
		CompanyID:  companyID,
		Filename:   filename,
		FilePath:   filePath,
		FileSize:   fileInfo.Size(),
		Status:     "completed",
		CreatedBy:  userID,
		IsAuto:     isAuto,
		TableCount: tableCount,
		RowCount:   totalRows,
	}

	err = s.repo.CreateBackupLog(backupLog)
	if err != nil {
		os.Remove(filePath)
		return nil, fmt.Errorf("error saving backup log: %w", err)
	}

	if isAuto {
		go s.cleanupOldBackups(companyID)
	}

	duration := time.Since(startTime)
	fmt.Printf("Backup completed: %s, %d tables, %d rows, %s\n", filename, tableCount, totalRows, duration)

	return backupLog, nil
}

func (s *BackupService) dumpTable(buf *bytes.Buffer, tableName string, companyID uuid.UUID, isCompanyTable, isChildTable bool) (int64, error) {
	var rows []map[string]interface{}
	var rowCount int64

	if isCompanyTable {
		err := s.db.Table(tableName).
			Where("company_id = ?", companyID).
			Find(&rows).Error
		if err != nil {
			return 0, err
		}
	} else if isChildTable {
		err := s.db.Table(tableName).Find(&rows).Error
		if err != nil {
			return 0, err
		}
	} else {
		err := s.db.Table(tableName).
			Where("company_id = ? OR company_id IS NULL", companyID).
			Find(&rows).Error
		if err != nil {
			return 0, err
		}
	}

	rowCount = int64(len(rows))
	if rowCount == 0 {
		return 0, nil
	}

	var columns []string
	for key := range rows[0] {
		if key != "deleted_at" {
			columns = append(columns, key)
		}
	}

	buf.WriteString(fmt.Sprintf("-- Table: %s (%d rows)\n", tableName, rowCount))
	buf.WriteString(fmt.Sprintf("COPY %s (%s) FROM stdin;\n", tableName, strings.Join(columns, ", ")))

	for _, row := range rows {
		var values []string
		for _, col := range columns {
			val := row[col]
			values = append(values, formatValue(val))
		}
		buf.WriteString(strings.Join(values, "\t") + "\n")
	}
	buf.WriteString("\\.\n\n")

	return rowCount, nil
}

func formatValue(val interface{}) string {
	if val == nil {
		return "\\N"
	}

	switch v := val.(type) {
	case time.Time:
		return v.Format("2006-01-02 15:04:05")
	case []byte:
		return strings.ReplaceAll(string(v), "\t", "\\t")
	case string:
		str := strings.ReplaceAll(v, "\\", "\\\\")
		str = strings.ReplaceAll(str, "\t", "\\t")
		str = strings.ReplaceAll(str, "\n", "\\n")
		str = strings.ReplaceAll(str, "\r", "\\r")
		if strings.ContainsAny(str, "\n\r\t\\") || str == "" {
			return str
		}
		return str
	default:
		return fmt.Sprintf("%v", v)
	}
}

func (s *BackupService) ListBackups(companyID uuid.UUID) ([]models.BackupLog, error) {
	return s.repo.GetBackupLogs(companyID, 100)
}

func (s *BackupService) DeleteBackup(companyID uuid.UUID, filename string) error {
	backupLog, err := s.repo.GetBackupLogByFilename(companyID, filename)
	if err != nil {
		return fmt.Errorf("backup not found")
	}

	err = os.Remove(backupLog.FilePath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("error deleting file: %w", err)
	}

	return s.repo.DeleteBackupLog(companyID, filename)
}

func (s *BackupService) GetBackupFilePath(companyID uuid.UUID, filename string) (string, error) {
	backupLog, err := s.repo.GetBackupLogByFilename(companyID, filename)
	if err != nil {
		return "", fmt.Errorf("backup not found")
	}

	if _, err := os.Stat(backupLog.FilePath); os.IsNotExist(err) {
		return "", fmt.Errorf("backup file not found on disk")
	}

	return backupLog.FilePath, nil
}

func (s *BackupService) ValidateRestore(companyID uuid.UUID, filename string) (*models.RestoreValidation, error) {
	backupLog, err := s.repo.GetBackupLogByFilename(companyID, filename)
	if err != nil {
		return &models.RestoreValidation{
			IsValid:      false,
			ErrorMessage: "Backup file not found",
		}, nil
	}

	fileInfo, err := os.Stat(backupLog.FilePath)
	if err != nil {
		return &models.RestoreValidation{
			IsValid:      false,
			ErrorMessage: "Backup file not found on disk",
		}, nil
	}

	maxFileSize := int64(500 * 1024 * 1024)
	if fileInfo.Size() > maxFileSize {
		return &models.RestoreValidation{
			IsValid:      false,
			ErrorMessage: "Backup file exceeds maximum size (500MB)",
		}, nil
	}

	companyName := s.getCompanyName(companyID)

	return &models.RestoreValidation{
		Filename:          filename,
		FileSize:          fileInfo.Size(),
		FileSizeFormatted: formatFileSize(fileInfo.Size()),
		CreatedAt:         backupLog.CreatedAt,
		TableCount:        backupLog.TableCount,
		RowCount:          backupLog.RowCount,
		CompanyID:         backupLog.CompanyID,
		CompanyName:       companyName,
		IsValid:           true,
	}, nil
}

func (s *BackupService) getCompanyName(companyID uuid.UUID) string {
	var company struct {
		Name string `gorm:"column:nama"`
	}
	if err := s.db.Table("companies").Where("id = ?", companyID).Select("nama").Scan(&company).Error; err != nil {
		return "Unknown"
	}
	if strings.TrimSpace(company.Name) == "" {
		return "Unknown"
	}
	return company.Name
}

func (s *BackupService) getCompanyCode(companyID uuid.UUID) string {
	var company struct {
		Code string `gorm:"column:code"`
	}
	if err := s.db.Table("companies").Where("id = ?", companyID).Select("code").Scan(&company).Error; err != nil {
		return ""
	}
	return strings.TrimSpace(company.Code)
}

func (s *BackupService) RestoreBackup(companyID uuid.UUID, companyCode, filename string, confirm bool) (*models.RestoreResult, error) {
	if !confirm {
		return nil, fmt.Errorf("confirmation required")
	}

	if companyCode == "" {
		companyCode = s.getCompanyCode(companyID)
	}
	if companyCode == "" {
		companyCode = companyID.String()[:8]
	}

	startTime := time.Now()

	safetyFilename, err := s.CreateBackup(companyID, companyCode, "system-safety", false)
	if err != nil {
		return nil, fmt.Errorf("failed to create safety backup: %w", err)
	}

	filePath, err := s.GetBackupFilePath(companyID, filename)
	if err != nil {
		return nil, err
	}

	tablesCleared, rowsRestored, err := s.importBackup(filePath, companyID)
	if err != nil {
		return nil, fmt.Errorf("restore failed: %w", err)
	}

	duration := time.Since(startTime)

	result := &models.RestoreResult{
		Status:        "success",
		CompanyID:     companyID,
		TablesCleared: tablesCleared,
		RowsRestored:  rowsRestored,
		Duration:      duration.String(),
		SafetyBackup:  safetyFilename.Filename,
	}

	return result, nil
}

func (s *BackupService) importBackup(filePath string, companyID uuid.UUID) (int, int64, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return 0, 0, err
	}
	defer file.Close()

	tx := s.db.Begin()
	if tx.Error != nil {
		return 0, 0, tx.Error
	}

	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	scanner := bufio.NewScanner(file)
	var currentTable string
	var columns []string
	var rowCount int64
	var tableCount int
	var inCopyBlock bool
	var values [][]string

	for scanner.Scan() {
		line := scanner.Text()

		if strings.HasPrefix(line, "COPY ") {
			parts := strings.Fields(line)
			if len(parts) >= 4 && parts[3] == "FROM" {
				currentTable = strings.TrimSuffix(parts[1], "(")
				colsPart := strings.TrimSuffix(strings.TrimPrefix(line, "COPY "+currentTable+" ("), ") FROM stdin;")
				columns = strings.Split(colsPart, ", ")
				inCopyBlock = true
				values = [][]string{}
				continue
			}
		}

		if inCopyBlock {
			if line == "\\." {
				if currentTable != "" && len(values) > 0 {
					cleared, rows, err := s.importTableData(tx, currentTable, columns, values, companyID)
					if err != nil {
						tx.Rollback()
						return tableCount, rowCount, err
					}
					if cleared {
						tableCount++
					}
					rowCount += rows
				}
				currentTable = ""
				columns = nil
				values = nil
				inCopyBlock = false
			} else if line != "" {
				rowValues := parseCSVLine(line)
				values = append(values, rowValues)
			}
		}
	}

	if err := scanner.Err(); err != nil {
		tx.Rollback()
		return tableCount, rowCount, err
	}

	if err := tx.Commit().Error; err != nil {
		return tableCount, rowCount, err
	}

	return tableCount, rowCount, nil
}

func parseCSVLine(line string) []string {
	r := csv.NewReader(strings.NewReader(line))
	r.Comma = '\t'
	r.LazyQuotes = true
	record, _ := r.Read()
	return record
}

func (s *BackupService) importTableData(tx *gorm.DB, tableName string, columns []string, values [][]string, companyID uuid.UUID) (bool, int64, error) {
	hasCompanyID := false
	for _, col := range columns {
		if col == "company_id" {
			hasCompanyID = true
			break
		}
	}

	if !hasCompanyID && !containsString(sharedTables, tableName) {
		return false, 0, nil
	}

	if containsString(companyTables, tableName) || containsString(sharedTables, tableName) {
		deleteQuery := fmt.Sprintf("DELETE FROM %s WHERE company_id = ?", tableName)
		if err := tx.Exec(deleteQuery, companyID).Error; err != nil {
			return false, 0, err
		}
	}

	if len(values) == 0 {
		return false, 0, nil
	}

	placeholders := make([]string, len(columns))
	colNames := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = "?"
		colNames[i] = columns[i]
	}

	insertQuery := fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES (%s) ON CONFLICT DO NOTHING",
		tableName,
		strings.Join(colNames, ", "),
		strings.Join(placeholders, ", "),
	)

	for _, row := range values {
		args := make([]interface{}, len(columns))
		for i, val := range row {
			if val == "\\N" || val == "" {
				args[i] = nil
			} else if strings.HasPrefix(val, "\\") {
				val = strings.ReplaceAll(val, "\\t", "\t")
				val = strings.ReplaceAll(val, "\\n", "\n")
				val = strings.ReplaceAll(val, "\\r", "\r")
				val = strings.ReplaceAll(val, "\\\\", "\\")
				args[i] = val
			} else {
				if strings.Contains(val, ".") {
					if _, err := time.Parse("2006-01-02 15:04:05", val); err == nil {
						t, _ := time.Parse("2006-01-02 15:04:05", val)
						args[i] = t
					} else {
						args[i] = val
					}
				} else if _, err := strconv.ParseInt(val, 10, 64); err == nil {
					args[i] = val
				} else {
					args[i] = val
				}
			}
		}

		if err := tx.Exec(insertQuery, args...).Error; err != nil {
			return false, 0, err
		}
	}

	return true, int64(len(values)), nil
}

func containsString(slice []string, str string) bool {
	for _, s := range slice {
		if s == str {
			return true
		}
	}
	return false
}

func (s *BackupService) cleanupOldBackups(companyID uuid.UUID) {
	schedule, err := s.repo.GetSchedule(companyID)
	if err != nil || schedule == nil {
		return
	}

	deletedFiles, err := s.repo.DeleteOldBackups(companyID, schedule.RetentionDays)
	if err != nil {
		fmt.Printf("Error cleaning up old backups: %v\n", err)
		return
	}

	for _, filename := range deletedFiles {
		backupLog, _ := s.repo.GetBackupLogByFilename(companyID, filename)
		if backupLog != nil {
			os.Remove(backupLog.FilePath)
		}
		fmt.Printf("Deleted old backup: %s\n", filename)
	}
}

func (s *BackupService) GetSchedule(companyID uuid.UUID) (*models.ScheduleResponse, error) {
	schedule, err := s.repo.GetSchedule(companyID)
	if err != nil {
		return nil, err
	}
	if schedule == nil {
		return &models.ScheduleResponse{
			CompanyID:     companyID,
			Enabled:       false,
			Schedule:      "0 2 * * *",
			RetentionDays: 7,
			Frequency:     "daily",
			Hour:          "2",
		}, nil
	}

	freq, day, hour := parseCronExpression(schedule.Schedule)

	return &models.ScheduleResponse{
		CompanyID:     schedule.CompanyID,
		Enabled:       schedule.Enabled,
		Schedule:      schedule.Schedule,
		RetentionDays: schedule.RetentionDays,
		LastBackupAt:  &schedule.LastBackupAt,
		Frequency:     freq,
		Day:           day,
		Hour:          hour,
	}, nil
}

func (s *BackupService) UpdateSchedule(companyID uuid.UUID, req *models.UpdateScheduleRequest) error {
	if req.RetentionDays <= 0 {
		req.RetentionDays = 7
	}

	cronSpec := strings.TrimSpace(req.Schedule)
	if req.Day != "" && req.Hour != "" {
		frequency := req.Frequency
		if frequency == "" {
			frequency = "daily"
		}
		cronSpec = buildCronExpression(frequency, req.Day, req.Hour)
	}
	if cronSpec == "" {
		cronSpec = "0 2 * * *"
	}

	schedule := &models.BackupSchedule{
		CompanyID:     companyID,
		Enabled:       req.Enabled,
		Schedule:      cronSpec,
		RetentionDays: req.RetentionDays,
	}

	err := s.repo.UpsertSchedule(schedule)
	if err != nil {
		return err
	}

	if req.Enabled {
		s.StartSchedule(companyID)
	} else {
		s.StopSchedule(companyID)
	}

	return nil
}

func (s *BackupService) StartSchedule(companyID uuid.UUID) {
	if entryID, exists := s.companyCrons[companyID]; exists {
		s.cron.Remove(entryID)
	}

	schedule, err := s.repo.GetSchedule(companyID)
	if err != nil || schedule == nil || !schedule.Enabled {
		return
	}

	job := cron.FuncJob(func() {
		companyCode := s.getCompanyCode(companyID)
		if _, err := s.CreateBackup(companyID, companyCode, "system-scheduler", true); err != nil {
			fmt.Printf("Scheduled backup failed for company %s: %v\n", companyID, err)
			return
		}
		if err := s.repo.UpdateLastBackup(companyID); err != nil {
			fmt.Printf("Failed to update last_backup_at for company %s: %v\n", companyID, err)
		}
		fmt.Printf("Scheduled backup completed for company: %s\n", companyID)
	})

	entryID, err := s.cron.AddFunc(schedule.Schedule, job)
	if err != nil {
		fmt.Printf("Error adding cron job: %v\n", err)
		return
	}

	s.companyCrons[companyID] = entryID
	fmt.Printf("Started scheduled backup for company %s with cron: %s\n", companyID, schedule.Schedule)
}

func (s *BackupService) StopSchedule(companyID uuid.UUID) {
	if entryID, exists := s.companyCrons[companyID]; exists {
		s.cron.Remove(entryID)
		delete(s.companyCrons, companyID)
		fmt.Printf("Stopped scheduled backup for company: %s\n", companyID)
	}
}

func (s *BackupService) StartAllSchedules() error {
	schedules, err := s.repo.GetAllEnabledSchedules()
	if err != nil {
		return err
	}

	for _, schedule := range schedules {
		s.StartSchedule(schedule.CompanyID)
	}

	s.cron.Start()
	fmt.Printf("Backup scheduler started with %d active schedules\n", len(schedules))
	return nil
}

func (s *BackupService) Stop() {
	s.cron.Stop()
}

func formatFileSize(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}

func parseCronExpression(cronStr string) (frequency, day, hour string) {
	parts := strings.Fields(cronStr)
	if len(parts) < 5 {
		return "daily", "", "2"
	}

	minute := parts[0]
	hourPart := parts[1]
	dayOfMonth := parts[2]
	_ = parts[3]
	dayOfWeek := parts[4]

	if dayOfWeek == "*" && dayOfMonth == "*" {
		frequency = "daily"
	} else if dayOfWeek != "*" {
		frequency = "weekly"
		day = dayOfWeek
	} else {
		frequency = "daily"
	}

	hour = hourPart
	if minute == "0" {
		hour = hourPart
	}

	return frequency, day, hour
}

func buildCronExpression(frequency, day, hour string) string {
	switch frequency {
	case "daily":
		return fmt.Sprintf("0 %s * * *", hour)
	case "weekly":
		return fmt.Sprintf("0 %s * * %s", hour, day)
	default:
		return "0 2 * * *"
	}
}

func ParseCronToHuman(cronStr string) string {
	freq, day, hour := parseCronExpression(cronStr)

	hourInt, _ := strconv.Atoi(hour)
	timeStr := fmt.Sprintf("%02d:00", hourInt)

	switch freq {
	case "daily":
		return fmt.Sprintf("setiap hari %s", timeStr)
	case "weekly":
		dayNames := map[string]string{
			"0": "Minggu",
			"1": "Senin",
			"2": "Selasa",
			"3": "Rabu",
			"4": "Kamis",
			"5": "Jumat",
			"6": "Sabtu",
		}
		dayName := dayNames[day]
		if dayName == "" {
			dayName = day
		}
		return fmt.Sprintf("setiap %s %s", dayName, timeStr)
	default:
		return "custom"
	}
}

func (s *BackupService) getTablesByScope(scope string) []string {
	switch scope {
	case "master":
		return masterTables
	case "transaction":
		return transactionTables
	case "all":
		allTables := make([]string, 0, len(masterTables)+len(transactionTables))
		allTables = append(allTables, masterTables...)
		allTables = append(allTables, transactionTables...)
		return allTables
	default:
		return masterTables
	}
}

func (s *BackupService) hasCompanyID(tableName string) bool {
	tablesWithCompanyID := map[string]bool{
		"users":             true,
		"warehouses":        true,
		"customers":         true,
		"suppliers":         true,
		"sales":             true,
		"sale_payments":     true,
		"purchase_orders":   true,
		"purchase_returns":  true,
		"invoices_incoming": true,
		"invoices_outgoing": true,
		"cash_drawers":      true,
		"stock_opnames":     true,
		"products":          true,
		"categories":        true,
	}
	return tablesWithCompanyID[tableName]
}

func (s *BackupService) GetTableCounts(companyID uuid.UUID, scope string) (*models.ScopeCountResponse, error) {
	tables := s.getTablesByScope(scope)
	var counts []models.TableCount
	var total int64

	for _, table := range tables {
		var count int64
		if s.hasCompanyID(table) {
			if err := s.db.Table(table).Where("company_id = ?", companyID).Count(&count).Error; err != nil {
				continue
			}
		} else {
			if err := s.db.Table(table).Count(&count).Error; err != nil {
				continue
			}
		}
		counts = append(counts, models.TableCount{
			TableName: table,
			RowCount:  count,
		})
		total += count
	}

	return &models.ScopeCountResponse{
		Scope:  scope,
		Tables: counts,
		Total:  total,
	}, nil
}

func (s *BackupService) DeleteData(companyID uuid.UUID, scope string) (*models.DeleteDataResponse, error) {
	tables := s.getTablesByScope(scope)

	deletedRecords := make(map[string]int64)
	var tablesCleared []string
	var totalRecords int64

	for _, table := range tables {
		var result *gorm.DB
		if s.hasCompanyID(table) {
			result = s.db.Table(table).Where("company_id = ?", companyID).Delete(nil)
		} else {
			result = s.db.Table(table).Delete(nil)
		}

		if result.Error != nil {
			return nil, fmt.Errorf("error deleting table %s: %w", table, result.Error)
		}

		rowsAffected := result.RowsAffected
		if rowsAffected > 0 {
			deletedRecords[table] = rowsAffected
			tablesCleared = append(tablesCleared, table)
			totalRecords += rowsAffected
		}
	}

	return &models.DeleteDataResponse{
		Scope:          scope,
		TablesCleared:  tablesCleared,
		RecordsDeleted: deletedRecords,
		TotalRecords:   totalRecords,
	}, nil
}
